package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"

	"github.com/vibe-c2/vibe-c2-core/core/pkg/graphql/generated"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/graphql/model"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/models"
)

// ID is the resolver for the id field.
func (r *agentActionResolver) ID(ctx context.Context, obj *models.AgentAction) (string, error) {
	return r.AgentActionResolver.ID(ctx, obj)
}

// OperationID is the resolver for the operationId field.
func (r *agentActionResolver) OperationID(ctx context.Context, obj *models.AgentAction) (*string, error) {
	return r.AgentActionResolver.OperationIDField(ctx, obj)
}

// Operation is the resolver for the operation field.
func (r *agentActionResolver) Operation(ctx context.Context, obj *models.AgentAction) (*models.Operation, error) {
	return r.AgentActionResolver.Operation(ctx, obj)
}

// AgentKeyID is the resolver for the agentKeyId field.
func (r *agentActionResolver) AgentKeyID(ctx context.Context, obj *models.AgentAction) (string, error) {
	return r.AgentActionResolver.AgentKeyIDField(ctx, obj)
}

// Outcome is the resolver for the outcome field.
func (r *agentActionResolver) Outcome(ctx context.Context, obj *models.AgentAction) (model.AgentActionOutcome, error) {
	return r.AgentActionResolver.Outcome(ctx, obj)
}

// Error is the resolver for the error field.
func (r *agentActionResolver) Error(ctx context.Context, obj *models.AgentAction) (*string, error) {
	return r.AgentActionResolver.Error(ctx, obj)
}

// DurationMs is the resolver for the durationMs field.
func (r *agentActionResolver) DurationMs(ctx context.Context, obj *models.AgentAction) (int, error) {
	return r.AgentActionResolver.DurationMs(ctx, obj)
}

// OccurredAt is the resolver for the occurredAt field.
func (r *agentActionResolver) OccurredAt(ctx context.Context, obj *models.AgentAction) (string, error) {
	return r.AgentActionResolver.OccurredAt(ctx, obj)
}

// MyAgentActions is the resolver for the myAgentActions field.
func (r *queryResolver) MyAgentActions(ctx context.Context, agentKeyID *string, operationID *string, writesOnly *bool, outcomes []model.AgentActionOutcome, before *string, limit *int) ([]*models.AgentAction, error) {
	return r.AgentActionResolver.MyAgentActions(ctx, agentKeyID, operationID, writesOnly, outcomes, before, limit)
}

// MyAgentActivitySummary is the resolver for the myAgentActivitySummary field.
func (r *queryResolver) MyAgentActivitySummary(ctx context.Context) ([]*model.AgentActivitySummary, error) {
	return r.AgentActionResolver.MyAgentActivitySummary(ctx)
}

// AgentAction returns generated.AgentActionResolver implementation.
func (r *Resolver) AgentAction() generated.AgentActionResolver { return &agentActionResolver{r} }

type agentActionResolver struct{ *Resolver }
