package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"

	"github.com/vibe-c2/vibe-c2-core/core/pkg/eventbus"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/graphql/gqlctx"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/graphql/model"
)

// AgentActivity is the resolver for the agentActivity field.
//
// Streams every MCP tool call an agent makes in this operation, reads
// included, so the operator can watch it work rather than only see the
// aftermath. Same bridge pattern as TimelineEventAdded, but without the
// refetch: the payload already carries everything the rail renders, and an
// agent running dozens of tools a minute should not put a database read on
// the hot path.
func (r *subscriptionResolver) AgentActivity(ctx context.Context, operationID string) (<-chan *model.AgentActivityEvent, error) {
	auth := gqlctx.AuthFromContext(ctx)
	if auth.UserID == "" {
		return nil, fmt.Errorf("unauthorized")
	}

	filter, err := r.buildOperationFilter(ctx, auth, &operationID)
	if err != nil {
		return nil, err
	}

	ch := make(chan *model.AgentActivityEvent, 1)

	unsubscribe := r.EventBus.Subscribe(
		[]eventbus.Topic{eventbus.TopicAgentAction},
		func(_ context.Context, event eventbus.Event) {
			p, ok := event.Payload.(eventbus.AgentActionPayload)
			if !ok {
				return
			}
			select {
			case ch <- &model.AgentActivityEvent{
				OperationID: p.OperationID,
				AgentKeyID:  p.AgentKeyID,
				AgentName:   p.AgentName,
				AgentLabel:  p.AgentLabel,
				OwnerUserID: p.OwnerUserID,
				Tool:        p.Tool,
				Write:       p.Write,
				Outcome:     p.Outcome,
				Summary:     p.Summary,
			}:
			case <-ctx.Done():
			}
		},
		filter,
	)

	go func() {
		<-ctx.Done()
		unsubscribe()
		close(ch)
	}()

	return ch, nil
}
