package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"

	"github.com/vibe-c2/vibe-c2-core/core/pkg/graphql/generated"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/graphql/model"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/models"
)

// ID is the resolver for the id field.
func (r *agentKeyResolver) ID(ctx context.Context, obj *models.AgentKey) (string, error) {
	return r.AgentKeyResolver.ID(ctx, obj)
}

// OperationScopes is the resolver for the operationScopes field.
func (r *agentKeyResolver) OperationScopes(ctx context.Context, obj *models.AgentKey) ([]*models.Operation, error) {
	return r.AgentKeyResolver.OperationScopes(ctx, obj)
}

// LastUsedAt is the resolver for the lastUsedAt field.
func (r *agentKeyResolver) LastUsedAt(ctx context.Context, obj *models.AgentKey) (*string, error) {
	return r.AgentKeyResolver.LastUsedAt(ctx, obj)
}

// CreatedAt is the resolver for the createdAt field.
func (r *agentKeyResolver) CreatedAt(ctx context.Context, obj *models.AgentKey) (string, error) {
	return r.AgentKeyResolver.CreatedAt(ctx, obj)
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *agentKeyResolver) UpdatedAt(ctx context.Context, obj *models.AgentKey) (string, error) {
	return r.AgentKeyResolver.UpdatedAt(ctx, obj)
}

// CreateAgentKey is the resolver for the createAgentKey field.
func (r *mutationResolver) CreateAgentKey(ctx context.Context, input model.CreateAgentKeyInput) (*model.AgentKeyWithSecret, error) {
	return r.AgentKeyResolver.CreateAgentKey(ctx, input)
}

// RegenerateAgentKey is the resolver for the regenerateAgentKey field.
func (r *mutationResolver) RegenerateAgentKey(ctx context.Context, id string) (*model.AgentKeyWithSecret, error) {
	return r.AgentKeyResolver.RegenerateAgentKey(ctx, id)
}

// UpdateAgentKey is the resolver for the updateAgentKey field.
func (r *mutationResolver) UpdateAgentKey(ctx context.Context, id string, input model.UpdateAgentKeyInput) (*models.AgentKey, error) {
	return r.AgentKeyResolver.UpdateAgentKey(ctx, id, input)
}

// SetAgentKeyEnabled is the resolver for the setAgentKeyEnabled field.
func (r *mutationResolver) SetAgentKeyEnabled(ctx context.Context, id string, enabled bool) (*models.AgentKey, error) {
	return r.AgentKeyResolver.SetAgentKeyEnabled(ctx, id, enabled)
}

// DeleteAgentKey is the resolver for the deleteAgentKey field.
func (r *mutationResolver) DeleteAgentKey(ctx context.Context, id string) (bool, error) {
	return r.AgentKeyResolver.DeleteAgentKey(ctx, id)
}

// MyAgentKeys is the resolver for the myAgentKeys field.
func (r *queryResolver) MyAgentKeys(ctx context.Context) ([]*models.AgentKey, error) {
	return r.AgentKeyResolver.MyAgentKeys(ctx)
}

// AgentKey returns generated.AgentKeyResolver implementation.
func (r *Resolver) AgentKey() generated.AgentKeyResolver { return &agentKeyResolver{r} }

type agentKeyResolver struct{ *Resolver }
