package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"

	"github.com/vibe-c2/vibe-c2-core/core/pkg/graphql/generated"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/graphql/model"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/models"
)

// ID is the resolver for the id field.
func (r *aPIKeyResolver) ID(ctx context.Context, obj *models.APIKey) (string, error) {
	return r.APIKeyResolver.ID(ctx, obj)
}

// LastUsedAt is the resolver for the lastUsedAt field.
func (r *aPIKeyResolver) LastUsedAt(ctx context.Context, obj *models.APIKey) (*string, error) {
	return r.APIKeyResolver.LastUsedAt(ctx, obj)
}

// CreatedAt is the resolver for the createdAt field.
func (r *aPIKeyResolver) CreatedAt(ctx context.Context, obj *models.APIKey) (string, error) {
	return r.APIKeyResolver.CreatedAt(ctx, obj)
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *aPIKeyResolver) UpdatedAt(ctx context.Context, obj *models.APIKey) (string, error) {
	return r.APIKeyResolver.UpdatedAt(ctx, obj)
}

// CreateMyAPIKey is the resolver for the createMyAPIKey field.
func (r *mutationResolver) CreateMyAPIKey(ctx context.Context) (*model.APIKeyWithSecret, error) {
	return r.APIKeyResolver.CreateMyAPIKey(ctx)
}

// RegenerateMyAPIKey is the resolver for the regenerateMyAPIKey field.
func (r *mutationResolver) RegenerateMyAPIKey(ctx context.Context) (*model.APIKeyWithSecret, error) {
	return r.APIKeyResolver.RegenerateMyAPIKey(ctx)
}

// SetMyAPIKeyEnabled is the resolver for the setMyAPIKeyEnabled field.
func (r *mutationResolver) SetMyAPIKeyEnabled(ctx context.Context, enabled bool) (*models.APIKey, error) {
	return r.APIKeyResolver.SetMyAPIKeyEnabled(ctx, enabled)
}

// DeleteMyAPIKey is the resolver for the deleteMyAPIKey field.
func (r *mutationResolver) DeleteMyAPIKey(ctx context.Context) (bool, error) {
	return r.APIKeyResolver.DeleteMyAPIKey(ctx)
}

// MyAPIKey is the resolver for the myAPIKey field.
func (r *queryResolver) MyAPIKey(ctx context.Context) (*models.APIKey, error) {
	return r.APIKeyResolver.MyAPIKey(ctx)
}

// APIKey returns generated.APIKeyResolver implementation.
func (r *Resolver) APIKey() generated.APIKeyResolver { return &aPIKeyResolver{r} }

type aPIKeyResolver struct{ *Resolver }
