package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/eventbus"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/graphql/generated"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/graphql/gqlctx"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/graphql/model"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/models"
)

// ID is the resolver for the id field.
func (r *credentialResolver) ID(ctx context.Context, obj *models.Credential) (string, error) {
	return r.CredentialResolver.ID(ctx, obj)
}

// OperationID is the resolver for the operationId field.
func (r *credentialResolver) OperationID(ctx context.Context, obj *models.Credential) (string, error) {
	return r.CredentialResolver.OperationIDField(ctx, obj)
}

// Operation is the resolver for the operation field.
func (r *credentialResolver) Operation(ctx context.Context, obj *models.Credential) (*models.Operation, error) {
	return r.CredentialResolver.Operation(ctx, obj)
}

// Comments is the resolver for the comments field.
func (r *credentialResolver) Comments(ctx context.Context, obj *models.Credential) ([]*models.CredentialComment, error) {
	return r.CredentialResolver.Comments(ctx, obj)
}

// ViewerCanModerateComments is the resolver for the viewerCanModerateComments field.
func (r *credentialResolver) ViewerCanModerateComments(ctx context.Context, obj *models.Credential) (bool, error) {
	return r.CredentialResolver.ViewerCanModerateComments(ctx, obj)
}

// CreatedBy is the resolver for the createdBy field.
func (r *credentialResolver) CreatedBy(ctx context.Context, obj *models.Credential) (*models.User, error) {
	return r.CredentialResolver.CreatedBy(ctx, obj)
}

// BacklinkCount is the resolver for the backlinkCount field.
func (r *credentialResolver) BacklinkCount(ctx context.Context, obj *models.Credential) (int, error) {
	return r.CredentialResolver.BacklinkCount(ctx, obj)
}

// Backlinks is the resolver for the backlinks field.
func (r *credentialResolver) Backlinks(ctx context.Context, obj *models.Credential) ([]*models.WikiDocument, error) {
	return r.CredentialResolver.Backlinks(ctx, obj)
}

// CreatedAt is the resolver for the createdAt field.
func (r *credentialResolver) CreatedAt(ctx context.Context, obj *models.Credential) (string, error) {
	return r.CredentialResolver.CreatedAt(ctx, obj)
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *credentialResolver) UpdatedAt(ctx context.Context, obj *models.Credential) (string, error) {
	return r.CredentialResolver.UpdatedAt(ctx, obj)
}

// ID is the resolver for the id field.
func (r *credentialCommentResolver) ID(ctx context.Context, obj *models.CredentialComment) (string, error) {
	return r.CredentialResolver.CommentID(ctx, obj)
}

// Author is the resolver for the author field.
func (r *credentialCommentResolver) Author(ctx context.Context, obj *models.CredentialComment) (*models.User, error) {
	return r.CredentialResolver.CommentAuthor(ctx, obj)
}

// CreatedAt is the resolver for the createdAt field.
func (r *credentialCommentResolver) CreatedAt(ctx context.Context, obj *models.CredentialComment) (string, error) {
	return r.CredentialResolver.CommentCreatedAt(ctx, obj)
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *credentialCommentResolver) UpdatedAt(ctx context.Context, obj *models.CredentialComment) (string, error) {
	return r.CredentialResolver.CommentUpdatedAt(ctx, obj)
}

// CreateCredential is the resolver for the createCredential field.
func (r *mutationResolver) CreateCredential(ctx context.Context, operationID string, input model.CreateCredentialInput) (*models.Credential, error) {
	return r.CredentialResolver.CreateCredential(ctx, operationID, input)
}

// UpdateCredential is the resolver for the updateCredential field.
func (r *mutationResolver) UpdateCredential(ctx context.Context, id string, input model.UpdateCredentialInput) (*models.Credential, error) {
	return r.CredentialResolver.UpdateCredential(ctx, id, input)
}

// DeleteCredential is the resolver for the deleteCredential field.
func (r *mutationResolver) DeleteCredential(ctx context.Context, id string) (bool, error) {
	return r.CredentialResolver.DeleteCredential(ctx, id)
}

// AddCredentialComment is the resolver for the addCredentialComment field.
func (r *mutationResolver) AddCredentialComment(ctx context.Context, credentialID string, text string) (*models.Credential, error) {
	return r.CredentialResolver.AddCredentialComment(ctx, credentialID, text)
}

// UpdateCredentialComment is the resolver for the updateCredentialComment field.
func (r *mutationResolver) UpdateCredentialComment(ctx context.Context, credentialID string, commentID string, text string) (*models.Credential, error) {
	return r.CredentialResolver.UpdateCredentialComment(ctx, credentialID, commentID, text)
}

// DeleteCredentialComment is the resolver for the deleteCredentialComment field.
func (r *mutationResolver) DeleteCredentialComment(ctx context.Context, credentialID string, commentID string) (*models.Credential, error) {
	return r.CredentialResolver.DeleteCredentialComment(ctx, credentialID, commentID)
}

// Credential is the resolver for the credential field.
func (r *queryResolver) Credential(ctx context.Context, id string) (*models.Credential, error) {
	return r.CredentialResolver.Credential(ctx, id)
}

// Credentials is the resolver for the credentials field.
func (r *queryResolver) Credentials(ctx context.Context, operationID string, search *string, searchFields []model.CredentialSearchField, typeArg *models.CredentialType, tags []string, validOnly *bool, sortBy *model.CredentialSortField, sortDirection *model.SortDirection, first *int, after *string, last *int, before *string) (*model.CredentialConnection, error) {
	return r.CredentialResolver.Credentials(ctx, operationID, search, searchFields, typeArg, tags, validOnly, sortBy, sortDirection, first, after, last, before)
}

// CredentialTags is the resolver for the credentialTags field.
func (r *queryResolver) CredentialTags(ctx context.Context, operationID string) ([]string, error) {
	return r.CredentialResolver.CredentialTags(ctx, operationID)
}

// MyCredentials is the resolver for the myCredentials field.
func (r *queryResolver) MyCredentials(ctx context.Context, operationIds []string, search *string, searchFields []model.CredentialSearchField, typeArg *models.CredentialType, tags []string, validOnly *bool, sortBy *model.CredentialSortField, sortDirection *model.SortDirection, first *int, after *string, last *int, before *string) (*model.CredentialConnection, error) {
	return r.CredentialResolver.MyCredentials(ctx, operationIds, search, searchFields, typeArg, tags, validOnly, sortBy, sortDirection, first, after, last, before)
}

// MyCredentialTags is the resolver for the myCredentialTags field.
func (r *queryResolver) MyCredentialTags(ctx context.Context, operationIds []string) ([]string, error) {
	return r.CredentialResolver.MyCredentialTags(ctx, operationIds)
}

// CredentialChanged is the resolver for the credentialChanged field.
//
// Same shape as wikiDocumentChanged: subscribe to credential events scoped
// to the given operation, fetch the full credential for non-delete events,
// and stream them to the client over SSE.
func (r *subscriptionResolver) CredentialChanged(ctx context.Context, operationID string) (<-chan *model.CredentialEvent, error) {
	auth := gqlctx.AuthFromContext(ctx)
	if auth.UserID == "" {
		return nil, fmt.Errorf("unauthorized")
	}

	filter, err := r.buildOperationFilter(ctx, auth, &operationID)
	if err != nil {
		return nil, err
	}

	ch := make(chan *model.CredentialEvent, 1)

	unsubscribe := r.EventBus.Subscribe(
		credentialTopics,
		func(_ context.Context, event eventbus.Event) {
			evt := toCredentialEvent(event)

			// For non-DELETE events, fetch the full credential so the
			// client gets fresh state without a follow-up query.
			if evt.Action != model.EventActionDeleted && r.CredentialRepo != nil {
				if cid, err := uuid.Parse(evt.CredentialID); err == nil {
					if cred, err := r.CredentialRepo.FindByID(ctx, cid); err == nil {
						evt.Credential = &cred
					}
				}
			}

			select {
			case ch <- evt:
			case <-ctx.Done():
			}
		},
		filter,
	)

	go func() {
		<-ctx.Done()
		unsubscribe()
		close(ch)
	}()

	return ch, nil
}

// MyCredentialChanged is the resolver for the myCredentialChanged field.
//
// Multi-operation sibling of CredentialChanged. Builds an operation-set filter
// from the operationIds argument (see buildOperationsFilter for the
// nil/empty/explicit semantics) and streams every matching credential event
// to the subscriber. For non-DELETE events we fetch the full credential here
// so the client can update its cache without a follow-up query.
func (r *subscriptionResolver) MyCredentialChanged(ctx context.Context, operationIds []string) (<-chan *model.CredentialEvent, error) {
	auth := gqlctx.AuthFromContext(ctx)
	if auth.UserID == "" {
		return nil, fmt.Errorf("unauthorized")
	}

	filter, err := r.buildOperationsFilter(ctx, auth, operationIds)
	if err != nil {
		return nil, err
	}

	ch := make(chan *model.CredentialEvent, 1)

	unsubscribe := r.EventBus.Subscribe(
		credentialTopics,
		func(_ context.Context, event eventbus.Event) {
			evt := toCredentialEvent(event)

			if evt.Action != model.EventActionDeleted && r.CredentialRepo != nil {
				if cid, err := uuid.Parse(evt.CredentialID); err == nil {
					if cred, err := r.CredentialRepo.FindByID(ctx, cid); err == nil {
						evt.Credential = &cred
					}
				}
			}

			select {
			case ch <- evt:
			case <-ctx.Done():
			}
		},
		filter,
	)

	go func() {
		<-ctx.Done()
		unsubscribe()
		close(ch)
	}()

	return ch, nil
}

// Credential returns generated.CredentialResolver implementation.
func (r *Resolver) Credential() generated.CredentialResolver { return &credentialResolver{r} }

// CredentialComment returns generated.CredentialCommentResolver implementation.
func (r *Resolver) CredentialComment() generated.CredentialCommentResolver {
	return &credentialCommentResolver{r}
}

type credentialResolver struct{ *Resolver }
type credentialCommentResolver struct{ *Resolver }
