package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"

	"github.com/vibe-c2/vibe-c2-core/core/pkg/graphql/model"
)

// PublishOperatorFocus is the resolver for the publishOperatorFocus field.
func (r *mutationResolver) PublishOperatorFocus(ctx context.Context, input model.OperatorFocusInput) (bool, error) {
	return r.FocusResolver.PublishOperatorFocus(ctx, input)
}

// MyOperatorFocus is the resolver for the myOperatorFocus field.
func (r *queryResolver) MyOperatorFocus(ctx context.Context) (*model.OperatorFocus, error) {
	return r.FocusResolver.MyOperatorFocus(ctx)
}
