package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/eventbus"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/graphql/generated"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/graphql/gqlctx"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/graphql/model"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/models"
)

// SourceHashes is the resolver for the sourceHashes field.
func (r *credentialResolver) SourceHashes(ctx context.Context, obj *models.Credential) ([]*models.Hash, error) {
	return r.HashResolver.SourceHashesForCredential(ctx, obj)
}

// ID is the resolver for the id field.
func (r *hashResolver) ID(ctx context.Context, obj *models.Hash) (string, error) {
	return r.HashResolver.ID(ctx, obj)
}

// OperationID is the resolver for the operationId field.
func (r *hashResolver) OperationID(ctx context.Context, obj *models.Hash) (string, error) {
	return r.HashResolver.OperationIDField(ctx, obj)
}

// Operation is the resolver for the operation field.
func (r *hashResolver) Operation(ctx context.Context, obj *models.Hash) (*models.Operation, error) {
	return r.HashResolver.Operation(ctx, obj)
}

// CredentialID is the resolver for the credentialId field.
func (r *hashResolver) CredentialID(ctx context.Context, obj *models.Hash) (*string, error) {
	return r.HashResolver.CredentialID(ctx, obj)
}

// Credential is the resolver for the credential field.
func (r *hashResolver) Credential(ctx context.Context, obj *models.Hash) (*models.Credential, error) {
	return r.HashResolver.Credential(ctx, obj)
}

// CreatedBy is the resolver for the createdBy field.
func (r *hashResolver) CreatedBy(ctx context.Context, obj *models.Hash) (*models.User, error) {
	return r.HashResolver.CreatedBy(ctx, obj)
}

// CreatedAt is the resolver for the createdAt field.
func (r *hashResolver) CreatedAt(ctx context.Context, obj *models.Hash) (string, error) {
	return r.HashResolver.CreatedAt(ctx, obj)
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *hashResolver) UpdatedAt(ctx context.Context, obj *models.Hash) (string, error) {
	return r.HashResolver.UpdatedAt(ctx, obj)
}

// CreateHash is the resolver for the createHash field.
func (r *mutationResolver) CreateHash(ctx context.Context, operationID string, input model.CreateHashInput) (*models.Hash, error) {
	return r.HashResolver.CreateHash(ctx, operationID, input)
}

// UpdateHash is the resolver for the updateHash field.
func (r *mutationResolver) UpdateHash(ctx context.Context, id string, input model.UpdateHashInput) (*models.Hash, error) {
	return r.HashResolver.UpdateHash(ctx, id, input)
}

// DeleteHash is the resolver for the deleteHash field.
func (r *mutationResolver) DeleteHash(ctx context.Context, id string) (bool, error) {
	return r.HashResolver.DeleteHash(ctx, id)
}

// BulkImportHashes is the resolver for the bulkImportHashes field.
func (r *mutationResolver) BulkImportHashes(ctx context.Context, operationID string, input model.BulkImportHashesInput) (*model.BulkImportHashesResult, error) {
	return r.HashResolver.BulkImportHashes(ctx, operationID, input)
}

// MarkHashCracked is the resolver for the markHashCracked field.
func (r *mutationResolver) MarkHashCracked(ctx context.Context, id string, input model.MarkHashCrackedInput) (*models.Hash, error) {
	return r.HashResolver.MarkHashCracked(ctx, id, input)
}

// Hash is the resolver for the hash field.
func (r *queryResolver) Hash(ctx context.Context, id string) (*models.Hash, error) {
	return r.HashResolver.Hash(ctx, id)
}

// Hashes is the resolver for the hashes field.
func (r *queryResolver) Hashes(ctx context.Context, operationID string, search *string, statuses []models.HashStatus, tags []string, hasCredential *bool, first *int, after *string, last *int, before *string) (*model.HashConnection, error) {
	return r.HashResolver.Hashes(ctx, operationID, search, statuses, tags, hasCredential, first, after, last, before)
}

// HashTags is the resolver for the hashTags field.
func (r *queryResolver) HashTags(ctx context.Context, operationID string) ([]string, error) {
	return r.HashResolver.HashTags(ctx, operationID)
}

// MyHashes is the resolver for the myHashes field.
func (r *queryResolver) MyHashes(ctx context.Context, operationIds []string, search *string, statuses []models.HashStatus, tags []string, hasCredential *bool, first *int, after *string, last *int, before *string) (*model.HashConnection, error) {
	return r.HashResolver.MyHashes(ctx, operationIds, search, statuses, tags, hasCredential, first, after, last, before)
}

// MyHashTags is the resolver for the myHashTags field.
func (r *queryResolver) MyHashTags(ctx context.Context, operationIds []string) ([]string, error) {
	return r.HashResolver.MyHashTags(ctx, operationIds)
}

// HashChanged is the resolver for the hashChanged field.
func (r *subscriptionResolver) HashChanged(ctx context.Context, operationID string) (<-chan *model.HashEvent, error) {
	auth := gqlctx.AuthFromContext(ctx)
	if auth.UserID == "" {
		return nil, fmt.Errorf("unauthorized")
	}

	filter, err := r.buildOperationFilter(ctx, auth, &operationID)
	if err != nil {
		return nil, err
	}

	ch := make(chan *model.HashEvent, 1)

	unsubscribe := r.EventBus.Subscribe(
		hashTopics,
		func(_ context.Context, event eventbus.Event) {
			evt := toHashEvent(event)

			if evt.Action != model.EventActionDeleted && evt.HashID != "" && r.HashRepo != nil {
				if hid, err := uuid.Parse(evt.HashID); err == nil {
					if h, err := r.HashRepo.FindByID(ctx, hid); err == nil {
						evt.Hash = &h
					}
				}
			}

			select {
			case ch <- evt:
			case <-ctx.Done():
			}
		},
		filter,
	)

	go func() {
		<-ctx.Done()
		unsubscribe()
		close(ch)
	}()

	return ch, nil
}

// MyHashChanged is the resolver for the myHashChanged field.
func (r *subscriptionResolver) MyHashChanged(ctx context.Context, operationIds []string) (<-chan *model.HashEvent, error) {
	auth := gqlctx.AuthFromContext(ctx)
	if auth.UserID == "" {
		return nil, fmt.Errorf("unauthorized")
	}

	filter, err := r.buildOperationsFilter(ctx, auth, operationIds)
	if err != nil {
		return nil, err
	}

	ch := make(chan *model.HashEvent, 1)

	unsubscribe := r.EventBus.Subscribe(
		hashTopics,
		func(_ context.Context, event eventbus.Event) {
			evt := toHashEvent(event)

			if evt.Action != model.EventActionDeleted && evt.HashID != "" && r.HashRepo != nil {
				if hid, err := uuid.Parse(evt.HashID); err == nil {
					if h, err := r.HashRepo.FindByID(ctx, hid); err == nil {
						evt.Hash = &h
					}
				}
			}

			select {
			case ch <- evt:
			case <-ctx.Done():
			}
		},
		filter,
	)

	go func() {
		<-ctx.Done()
		unsubscribe()
		close(ch)
	}()

	return ch, nil
}

// Hash returns generated.HashResolver implementation.
func (r *Resolver) Hash() generated.HashResolver { return &hashResolver{r} }

type hashResolver struct{ *Resolver }
