package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"

	"github.com/vibe-c2/vibe-c2-core/core/pkg/eventbus"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/graphql/generated"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/graphql/gqlctx"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/graphql/model"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/models"
)

// RegisteredAt is the resolver for the registeredAt field.
func (r *moduleResolver) RegisteredAt(ctx context.Context, obj *models.Module) (string, error) {
	return r.ModuleResolver.RegisteredAt(ctx, obj)
}

// LastHeartbeatAt is the resolver for the lastHeartbeatAt field.
func (r *moduleResolver) LastHeartbeatAt(ctx context.Context, obj *models.Module) (*string, error) {
	return r.ModuleResolver.LastHeartbeatAt(ctx, obj)
}

// DeregisteredAt is the resolver for the deregisteredAt field.
func (r *moduleResolver) DeregisteredAt(ctx context.Context, obj *models.Module) (*string, error) {
	return r.ModuleResolver.DeregisteredAt(ctx, obj)
}

// DeclaredDeadAt is the resolver for the declaredDeadAt field.
func (r *moduleResolver) DeclaredDeadAt(ctx context.Context, obj *models.Module) (*string, error) {
	return r.ModuleResolver.DeclaredDeadAt(ctx, obj)
}

// RemoveModule is the resolver for the removeModule field.
func (r *mutationResolver) RemoveModule(ctx context.Context, instance string) (*models.Module, error) {
	return r.ModuleResolver.RemoveModule(ctx, instance)
}

// Modules is the resolver for the modules field.
func (r *queryResolver) Modules(ctx context.Context, status []string) ([]*models.Module, error) {
	return r.ModuleResolver.Modules(ctx, status)
}

// ModuleChanged is the resolver for the moduleChanged field.
//
// Admin-only real-time stream for the Modules page. Unlike the operation-scoped
// subscriptions there is no membership filter — authorization is the
// @hasPermission(module:read) directive. Every event refetches the full module
// row (which is never hard-deleted) so the client updates without a follow-up
// query.
func (r *subscriptionResolver) ModuleChanged(ctx context.Context) (<-chan *model.ModuleEvent, error) {
	auth := gqlctx.AuthFromContext(ctx)
	if auth.UserID == "" {
		return nil, fmt.Errorf("unauthorized")
	}

	ch := make(chan *model.ModuleEvent, 1)

	unsubscribe := r.EventBus.Subscribe(
		moduleTopics,
		func(_ context.Context, event eventbus.Event) {
			evt := toModuleEvent(event)

			if r.ModuleRepo != nil && evt.Instance != "" {
				if mod, err := r.ModuleRepo.FindByInstance(ctx, evt.Instance); err == nil {
					evt.Module = &mod
				}
			}

			select {
			case ch <- evt:
			case <-ctx.Done():
			}
		},
	)

	go func() {
		<-ctx.Done()
		unsubscribe()
		close(ch)
	}()

	return ch, nil
}

// Module returns generated.ModuleResolver implementation.
func (r *Resolver) Module() generated.ModuleResolver { return &moduleResolver{r} }

type moduleResolver struct{ *Resolver }
