package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"

	"github.com/vibe-c2/vibe-c2-core/core/pkg/graphql/generated"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/graphql/model"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/models"
)

// CreateUser handles the createUser mutation.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*models.User, error) {
	return r.UserResolver.CreateUser(ctx, input)
}

// UpdateUser handles the updateUser mutation.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, input model.UpdateUserInput) (*models.User, error) {
	return r.UserResolver.UpdateUser(ctx, id, input)
}

// DeleteUser handles the deleteUser mutation.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	return r.UserResolver.DeleteUser(ctx, id)
}

// UpdateOwnProfile lets a user update their own account.
func (r *mutationResolver) UpdateOwnProfile(ctx context.Context, input model.UpdateUserInput) (*models.User, error) {
	return r.UserResolver.UpdateOwnProfile(ctx, input)
}

// CreateOperation creates a new operation.
func (r *mutationResolver) CreateOperation(ctx context.Context, input model.CreateOperationInput) (*models.Operation, error) {
	return r.OperationResolver.CreateOperation(ctx, input)
}

// UpdateOperation modifies an existing operation's name or description.
func (r *mutationResolver) UpdateOperation(ctx context.Context, id string, input model.UpdateOperationInput) (*models.Operation, error) {
	return r.OperationResolver.UpdateOperation(ctx, id, input)
}

// DeleteOperation removes an operation by ID.
func (r *mutationResolver) DeleteOperation(ctx context.Context, id string) (bool, error) {
	return r.OperationResolver.DeleteOperation(ctx, id)
}

// AddOperationMember assigns a user to an operation with the given role.
func (r *mutationResolver) AddOperationMember(ctx context.Context, operationID string, userID string, role models.OperationRole) (*models.Operation, error) {
	return r.OperationResolver.AddOperationMember(ctx, operationID, userID, role)
}

// RemoveOperationMember removes a user from an operation.
func (r *mutationResolver) RemoveOperationMember(ctx context.Context, operationID string, userID string) (*models.Operation, error) {
	return r.OperationResolver.RemoveOperationMember(ctx, operationID, userID)
}

// UpdateOperationMemberRole changes a member's role in an operation.
func (r *mutationResolver) UpdateOperationMemberRole(ctx context.Context, operationID string, userID string, role models.OperationRole) (*models.Operation, error) {
	return r.OperationResolver.UpdateOperationMemberRole(ctx, operationID, userID, role)
}

// CreateSchemeNetworkPoint creates a new network point in an operation.
func (r *mutationResolver) CreateSchemeNetworkPoint(ctx context.Context, operationID string, input model.CreateSchemeNetworkPointInput) (*models.SchemeNetworkPoint, error) {
	return r.SchemeNetworkPointResolver.CreateSchemeNetworkPoint(ctx, operationID, input)
}

// UpdateSchemeNetworkPoint modifies an existing network point.
func (r *mutationResolver) UpdateSchemeNetworkPoint(ctx context.Context, id string, input model.UpdateSchemeNetworkPointInput) (*models.SchemeNetworkPoint, error) {
	return r.SchemeNetworkPointResolver.UpdateSchemeNetworkPoint(ctx, id, input)
}

// DeleteSchemeNetworkPoint removes a network point by ID.
func (r *mutationResolver) DeleteSchemeNetworkPoint(ctx context.Context, id string) (bool, error) {
	return r.SchemeNetworkPointResolver.DeleteSchemeNetworkPoint(ctx, id)
}

// AddSchemeNetworkPort adds a port to a network point.
func (r *mutationResolver) AddSchemeNetworkPort(ctx context.Context, pointID string, input model.CreateSchemeNetworkPortInput) (*models.SchemeNetworkPoint, error) {
	return r.SchemeNetworkPointResolver.AddSchemeNetworkPort(ctx, pointID, input)
}

// UpdateSchemeNetworkPort updates a port on a network point.
func (r *mutationResolver) UpdateSchemeNetworkPort(ctx context.Context, pointID string, portID string, input model.UpdateSchemeNetworkPortInput) (*models.SchemeNetworkPoint, error) {
	return r.SchemeNetworkPointResolver.UpdateSchemeNetworkPort(ctx, pointID, portID, input)
}

// RemoveSchemeNetworkPort removes a port from a network point.
func (r *mutationResolver) RemoveSchemeNetworkPort(ctx context.Context, pointID string, portID string) (*models.SchemeNetworkPoint, error) {
	return r.SchemeNetworkPointResolver.RemoveSchemeNetworkPort(ctx, pointID, portID)
}

// ID converts the Operation's UUID to a GraphQL ID string.
func (r *operationResolver) ID(ctx context.Context, obj *models.Operation) (string, error) {
	return r.OperationResolver.ID(ctx, obj)
}

// Members resolves the operation's member_ids into full User objects.
func (r *operationResolver) Members(ctx context.Context, obj *models.Operation) ([]*models.OperationMember, error) {
	return r.OperationResolver.Members(ctx, obj)
}

// CreatedAt converts the qmgo DefaultField timestamp to an ISO 8601 string.
func (r *operationResolver) CreatedAt(ctx context.Context, obj *models.Operation) (string, error) {
	return r.OperationResolver.CreatedAt(ctx, obj)
}

// UpdatedAt converts the qmgo DefaultField timestamp to an ISO 8601 string.
func (r *operationResolver) UpdatedAt(ctx context.Context, obj *models.Operation) (string, error) {
	return r.OperationResolver.UpdatedAt(ctx, obj)
}

// User resolves the full User object for an OperationMember.
func (r *operationMemberResolver) User(ctx context.Context, obj *models.OperationMember) (*models.User, error) {
	return r.OperationResolver.OperationMemberUser(ctx, obj)
}

// Me returns the currently authenticated user.
func (r *queryResolver) Me(ctx context.Context) (*models.User, error) {
	return r.UserResolver.Me(ctx)
}

// User returns a single user by their ID.
func (r *queryResolver) User(ctx context.Context, id string) (*models.User, error) {
	return r.UserResolver.User(ctx, id)
}

// Users returns a paginated list of users with optional search.
func (r *queryResolver) Users(ctx context.Context, search *string, offset *int, limit *int) (*model.UserPagination, error) {
	return r.UserResolver.Users(ctx, search, offset, limit)
}

// Operation returns a single operation by its ID.
func (r *queryResolver) Operation(ctx context.Context, id string) (*models.Operation, error) {
	return r.OperationResolver.Operation(ctx, id)
}

// Operations returns a paginated list of operations with optional search.
func (r *queryResolver) Operations(ctx context.Context, search *string, offset *int, limit *int) (*model.OperationPagination, error) {
	return r.OperationResolver.Operations(ctx, search, offset, limit)
}

// MyOperationRole returns the caller's role in a specific operation.
func (r *queryResolver) MyOperationRole(ctx context.Context, operationID string) (*models.OperationRole, error) {
	return r.OperationResolver.MyOperationRole(ctx, operationID)
}

// SchemeNetworkPoint returns a single network point by ID.
func (r *queryResolver) SchemeNetworkPoint(ctx context.Context, id string) (*models.SchemeNetworkPoint, error) {
	return r.SchemeNetworkPointResolver.SchemeNetworkPoint(ctx, id)
}

// SchemeNetworkPoints returns a paginated list of network points for an operation.
func (r *queryResolver) SchemeNetworkPoints(ctx context.Context, operationID string, search *string, offset *int, limit *int) (*model.SchemeNetworkPointPagination, error) {
	return r.SchemeNetworkPointResolver.SchemeNetworkPoints(ctx, operationID, search, offset, limit)
}

// ID converts the SchemeNetworkPoint's UUID to a GraphQL ID string.
func (r *schemeNetworkPointResolver) ID(ctx context.Context, obj *models.SchemeNetworkPoint) (string, error) {
	return r.SchemeNetworkPointResolver.ID(ctx, obj)
}

// OperationID converts the OperationID UUID to a GraphQL ID string.
func (r *schemeNetworkPointResolver) OperationID(ctx context.Context, obj *models.SchemeNetworkPoint) (string, error) {
	return r.SchemeNetworkPointResolver.OperationIDField(ctx, obj)
}

// Ports returns the network point's port list as pointers for GraphQL resolution.
func (r *schemeNetworkPointResolver) Ports(ctx context.Context, obj *models.SchemeNetworkPoint) ([]*models.SchemeNetworkPort, error) {
	return r.SchemeNetworkPointResolver.Ports(ctx, obj)
}

// CreatedAt converts the qmgo DefaultField timestamp to an ISO 8601 string.
func (r *schemeNetworkPointResolver) CreatedAt(ctx context.Context, obj *models.SchemeNetworkPoint) (string, error) {
	return r.SchemeNetworkPointResolver.CreatedAt(ctx, obj)
}

// UpdatedAt converts the qmgo DefaultField timestamp to an ISO 8601 string.
func (r *schemeNetworkPointResolver) UpdatedAt(ctx context.Context, obj *models.SchemeNetworkPoint) (string, error) {
	return r.SchemeNetworkPointResolver.UpdatedAt(ctx, obj)
}

// ID converts the SchemeNetworkPort's UUID to a GraphQL ID string.
func (r *schemeNetworkPortResolver) ID(ctx context.Context, obj *models.SchemeNetworkPort) (string, error) {
	return r.SchemeNetworkPointResolver.PortID(ctx, obj)
}

// ID converts the User's UUID to a GraphQL ID string.
func (r *userResolver) ID(ctx context.Context, obj *models.User) (string, error) {
	return r.UserResolver.ID(ctx, obj)
}

// CreatedAt converts the qmgo DefaultField timestamp to an ISO 8601 string.
func (r *userResolver) CreatedAt(ctx context.Context, obj *models.User) (string, error) {
	return r.UserResolver.CreatedAt(ctx, obj)
}

// UpdatedAt converts the qmgo DefaultField timestamp to an ISO 8601 string.
func (r *userResolver) UpdatedAt(ctx context.Context, obj *models.User) (string, error) {
	return r.UserResolver.UpdatedAt(ctx, obj)
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Operation returns generated.OperationResolver implementation.
func (r *Resolver) Operation() generated.OperationResolver { return &operationResolver{r} }

// OperationMember returns generated.OperationMemberResolver implementation.
func (r *Resolver) OperationMember() generated.OperationMemberResolver {
	return &operationMemberResolver{r}
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// SchemeNetworkPoint returns generated.SchemeNetworkPointResolver implementation.
func (r *Resolver) SchemeNetworkPoint() generated.SchemeNetworkPointResolver {
	return &schemeNetworkPointResolver{r}
}

// SchemeNetworkPort returns generated.SchemeNetworkPortResolver implementation.
func (r *Resolver) SchemeNetworkPort() generated.SchemeNetworkPortResolver {
	return &schemeNetworkPortResolver{r}
}

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type mutationResolver struct{ *Resolver }
type operationResolver struct{ *Resolver }
type operationMemberResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type schemeNetworkPointResolver struct{ *Resolver }
type schemeNetworkPortResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
