package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/auth"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/graphql/generated"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/graphql/model"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/models"
)

// CreateUser handles the createUser mutation.
// By the time this runs, @hasPermission has already verified "user:create".
//
// Example GraphQL call:
//
//	mutation {
//	    createUser(input: { username: "bob", password: "s3cret", roles: ["user"] }) {
//	        id username roles active
//	    }
//	}
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*models.User, error) {
	// Check if username is already taken (same check as enroll controller)
	exists, err := r.UserRepo.ExistsByUsername(ctx, input.Username)
	if err != nil {
		return nil, fmt.Errorf("failed to check username: %w", err)
	}
	if exists {
		return nil, fmt.Errorf("username '%s' already exists", input.Username)
	}

	// Hash the password with bcrypt (same function used by the enroll controller)
	hashedPassword, err := auth.HashPassword(input.Password)
	if err != nil {
		return nil, fmt.Errorf("failed to hash password: %w", err)
	}

	// Default active to true if the client didn't specify it.
	// In the schema, active has a default value of true, but gqlgen sends
	// it as a *bool (pointer) so we need to handle the nil case.
	active := true
	if input.Active != nil {
		active = *input.Active
	}

	user := &models.User{
		UserID:   uuid.New(),
		Username: input.Username,
		Password: hashedPassword,
		Roles:    input.Roles,
		Active:   active,
	}

	if err := r.UserRepo.Create(ctx, user); err != nil {
		return nil, fmt.Errorf("failed to create user: %w", err)
	}

	return user, nil
}

// UpdateUser handles the updateUser mutation.
// Only fields that the client sends (non-nil) are updated.
//
// Example:
//
//	mutation {
//	    updateUser(id: "some-uuid", input: { active: false }) {
//	        id username active
//	    }
//	}
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, input model.UpdateUserInput) (*models.User, error) {
	uid, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %w", err)
	}

	user, err := r.UserRepo.FindByID(ctx, uid)
	if err != nil {
		return nil, fmt.Errorf("user not found: %w", err)
	}

	// Build a map of only the fields the client wants to change.
	// This is the "partial update" pattern — null fields are ignored.
	updates := buildUpdateMap(input)
	if len(updates) == 0 {
		return &user, nil
	}

	// If the password is being updated, hash it before storing
	if rawPwd, ok := updates["password"]; ok {
		hashed, err := auth.HashPassword(rawPwd.(string))
		if err != nil {
			return nil, fmt.Errorf("failed to hash password: %w", err)
		}
		updates["password"] = hashed
	}

	if err := r.UserRepo.Update(ctx, &user, updates); err != nil {
		return nil, fmt.Errorf("failed to update user: %w", err)
	}

	// Re-fetch to return the updated state
	updated, err := r.UserRepo.FindByID(ctx, uid)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch updated user: %w", err)
	}

	return &updated, nil
}

// DeleteUser handles the deleteUser mutation.
// Returns true on success.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	uid, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid user ID: %w", err)
	}

	user, err := r.UserRepo.FindByID(ctx, uid)
	if err != nil {
		return false, fmt.Errorf("user not found: %w", err)
	}

	if err := r.UserRepo.Delete(ctx, &user); err != nil {
		return false, fmt.Errorf("failed to delete user: %w", err)
	}
	return true, nil
}

// UpdateOwnProfile lets a user update their own account.
// The user ID comes from the JWT (not from the client input) to prevent
// users from modifying other users' profiles.
func (r *mutationResolver) UpdateOwnProfile(ctx context.Context, input model.UpdateUserInput) (*models.User, error) {
	authInfo := AuthFromContext(ctx)
	uid, err := uuid.Parse(authInfo.UserID)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID in token: %w", err)
	}

	user, err := r.UserRepo.FindByID(ctx, uid)
	if err != nil {
		return nil, fmt.Errorf("user not found: %w", err)
	}

	// Build update map but exclude "roles" — regular users should not
	// be able to escalate their own privileges.
	updates := buildUpdateMap(input)
	delete(updates, "roles")

	if len(updates) == 0 {
		return &user, nil
	}

	// Hash password if being updated
	if rawPwd, ok := updates["password"]; ok {
		hashed, err := auth.HashPassword(rawPwd.(string))
		if err != nil {
			return nil, fmt.Errorf("failed to hash password: %w", err)
		}
		updates["password"] = hashed
	}

	if err := r.UserRepo.Update(ctx, &user, updates); err != nil {
		return nil, fmt.Errorf("failed to update profile: %w", err)
	}

	// Re-fetch to return the updated state
	updated, err := r.UserRepo.FindByID(ctx, uid)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch updated user: %w", err)
	}

	return &updated, nil
}

// CreateOperation creates a new operation.
//
// Example:
//
//	mutation {
//	    createOperation(input: { name: "Red Dawn", description: "APT simulation" }) {
//	        id name description members { id username }
//	    }
//	}
func (r *mutationResolver) CreateOperation(ctx context.Context, input model.CreateOperationInput) (*models.Operation, error) {
	description := ""
	if input.Description != nil {
		description = *input.Description
	}

	op := &models.Operation{
		OperationID: uuid.New(),
		Name:        input.Name,
		Description: description,
		MemberIDs:   []uuid.UUID{},
	}

	if err := r.OperationRepo.Create(ctx, op); err != nil {
		return nil, fmt.Errorf("failed to create operation: %w", err)
	}

	return op, nil
}

// UpdateOperation modifies an existing operation's name or description.
func (r *mutationResolver) UpdateOperation(ctx context.Context, id string, input model.UpdateOperationInput) (*models.Operation, error) {
	uid, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid operation ID: %w", err)
	}

	op, err := r.OperationRepo.FindByID(ctx, uid)
	if err != nil {
		return nil, fmt.Errorf("operation not found: %w", err)
	}

	updates := make(map[string]interface{})
	if input.Name != nil {
		updates["name"] = *input.Name
	}
	if input.Description != nil {
		updates["description"] = *input.Description
	}

	if len(updates) == 0 {
		return &op, nil
	}

	if err := r.OperationRepo.Update(ctx, &op, updates); err != nil {
		return nil, fmt.Errorf("failed to update operation: %w", err)
	}

	updated, err := r.OperationRepo.FindByID(ctx, uid)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch updated operation: %w", err)
	}

	return &updated, nil
}

// DeleteOperation removes an operation by ID.
func (r *mutationResolver) DeleteOperation(ctx context.Context, id string) (bool, error) {
	uid, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid operation ID: %w", err)
	}

	op, err := r.OperationRepo.FindByID(ctx, uid)
	if err != nil {
		return false, fmt.Errorf("operation not found: %w", err)
	}

	if err := r.OperationRepo.Delete(ctx, &op); err != nil {
		return false, fmt.Errorf("failed to delete operation: %w", err)
	}
	return true, nil
}

// AddOperationMember assigns a user to an operation.
// Validates that both the operation and user exist before adding.
func (r *mutationResolver) AddOperationMember(ctx context.Context, operationID string, userID string) (*models.Operation, error) {
	opUID, err := uuid.Parse(operationID)
	if err != nil {
		return nil, fmt.Errorf("invalid operation ID: %w", err)
	}

	userUID, err := uuid.Parse(userID)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %w", err)
	}

	// Verify operation exists
	if _, err := r.OperationRepo.FindByID(ctx, opUID); err != nil {
		return nil, fmt.Errorf("operation not found: %w", err)
	}

	// Verify user exists
	if _, err := r.UserRepo.FindByID(ctx, userUID); err != nil {
		return nil, fmt.Errorf("user not found: %w", err)
	}

	// $addToSet is idempotent — adding an existing member is a no-op
	if err := r.OperationRepo.AddMember(ctx, opUID, userUID); err != nil {
		return nil, fmt.Errorf("failed to add member: %w", err)
	}

	updated, err := r.OperationRepo.FindByID(ctx, opUID)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch updated operation: %w", err)
	}

	return &updated, nil
}

// RemoveOperationMember removes a user from an operation.
func (r *mutationResolver) RemoveOperationMember(ctx context.Context, operationID string, userID string) (*models.Operation, error) {
	opUID, err := uuid.Parse(operationID)
	if err != nil {
		return nil, fmt.Errorf("invalid operation ID: %w", err)
	}

	userUID, err := uuid.Parse(userID)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %w", err)
	}

	// Verify operation exists
	if _, err := r.OperationRepo.FindByID(ctx, opUID); err != nil {
		return nil, fmt.Errorf("operation not found: %w", err)
	}

	// $pull is idempotent — removing a non-member is a no-op
	if err := r.OperationRepo.RemoveMember(ctx, opUID, userUID); err != nil {
		return nil, fmt.Errorf("failed to remove member: %w", err)
	}

	updated, err := r.OperationRepo.FindByID(ctx, opUID)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch updated operation: %w", err)
	}

	return &updated, nil
}

// ID converts the Operation's UUID to a GraphQL ID string.
func (r *operationResolver) ID(ctx context.Context, obj *models.Operation) (string, error) {
	return obj.OperationID.String(), nil
}

// Members resolves the operation's member_ids into full User objects.
// This is the many-to-many "join" — we fetch each user by their UUID.
func (r *operationResolver) Members(ctx context.Context, obj *models.Operation) ([]*models.User, error) {
	if len(obj.MemberIDs) == 0 {
		return []*models.User{}, nil
	}

	members := make([]*models.User, 0, len(obj.MemberIDs))
	for _, uid := range obj.MemberIDs {
		user, err := r.UserRepo.FindByID(ctx, uid)
		if err != nil {
			// Skip users that no longer exist (e.g. deleted after being added)
			continue
		}
		members = append(members, &user)
	}

	return members, nil
}

// CreatedAt converts the qmgo DefaultField timestamp to an ISO 8601 string.
func (r *operationResolver) CreatedAt(ctx context.Context, obj *models.Operation) (string, error) {
	return obj.CreateAt.Format(time.RFC3339), nil
}

// UpdatedAt converts the qmgo DefaultField timestamp to an ISO 8601 string.
func (r *operationResolver) UpdatedAt(ctx context.Context, obj *models.Operation) (string, error) {
	return obj.UpdateAt.Format(time.RFC3339), nil
}

// Me returns the currently authenticated user.
// The user ID is extracted from the JWT token in the context.
func (r *queryResolver) Me(ctx context.Context) (*models.User, error) {
	authInfo := AuthFromContext(ctx)
	uid, err := uuid.Parse(authInfo.UserID)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID in token: %w", err)
	}

	user, err := r.UserRepo.FindByID(ctx, uid)
	if err != nil {
		return nil, fmt.Errorf("user not found: %w", err)
	}
	return &user, nil
}

// User returns a single user by their ID.
func (r *queryResolver) User(ctx context.Context, id string) (*models.User, error) {
	uid, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %w", err)
	}

	user, err := r.UserRepo.FindByID(ctx, uid)
	if err != nil {
		return nil, fmt.Errorf("user not found: %w", err)
	}
	return &user, nil
}

// Users returns a paginated list of users with optional search.
//
// Example:
//
//	query {
//	    users(search: "admin", offset: 0, limit: 10) {
//	        totalCount
//	        users { id username roles active }
//	    }
//	}
func (r *queryResolver) Users(ctx context.Context, search *string, offset *int, limit *int) (*model.UserPagination, error) {
	// Apply defaults for optional pagination parameters.
	s := ""
	if search != nil {
		s = *search
	}
	off := int64(0)
	if offset != nil {
		off = int64(*offset)
	}
	lim := int64(20)
	if limit != nil {
		lim = int64(*limit)
	}

	total, err := r.UserRepo.Count(ctx, s)
	if err != nil {
		return nil, fmt.Errorf("failed to count users: %w", err)
	}

	users, err := r.UserRepo.FindAll(ctx, s, off, lim)
	if err != nil {
		return nil, fmt.Errorf("failed to list users: %w", err)
	}

	// Convert []models.User to []*models.User (gqlgen uses pointers).
	ptrs := make([]*models.User, len(users))
	for i := range users {
		ptrs[i] = &users[i]
	}

	// Compute pagination flags for the frontend.
	// hasNextPage:     true if there are more users beyond this page
	// hasPreviousPage: true if we skipped some users (offset > 0)
	hasNext := off+lim < total
	hasPrev := off > 0

	return &model.UserPagination{
		Users:           ptrs,
		TotalCount:      int(total),
		HasNextPage:     hasNext,
		HasPreviousPage: hasPrev,
	}, nil
}

// Operation returns a single operation by its ID.
func (r *queryResolver) Operation(ctx context.Context, id string) (*models.Operation, error) {
	uid, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid operation ID: %w", err)
	}

	op, err := r.OperationRepo.FindByID(ctx, uid)
	if err != nil {
		return nil, fmt.Errorf("operation not found: %w", err)
	}
	return &op, nil
}

// Operations returns a paginated list of operations with optional search.
//
// Example:
//
//	query {
//	    operations(search: "red", limit: 10) {
//	        totalCount
//	        operations { id name description members { id username } }
//	    }
//	}
func (r *queryResolver) Operations(ctx context.Context, search *string, offset *int, limit *int) (*model.OperationPagination, error) {
	s := ""
	if search != nil {
		s = *search
	}
	off := int64(0)
	if offset != nil {
		off = int64(*offset)
	}
	lim := int64(20)
	if limit != nil {
		lim = int64(*limit)
	}

	total, err := r.OperationRepo.Count(ctx, s)
	if err != nil {
		return nil, fmt.Errorf("failed to count operations: %w", err)
	}

	ops, err := r.OperationRepo.FindAll(ctx, s, off, lim)
	if err != nil {
		return nil, fmt.Errorf("failed to list operations: %w", err)
	}

	ptrs := make([]*models.Operation, len(ops))
	for i := range ops {
		ptrs[i] = &ops[i]
	}

	hasNext := off+lim < total
	hasPrev := off > 0

	return &model.OperationPagination{
		Operations:      ptrs,
		TotalCount:      int(total),
		HasNextPage:     hasNext,
		HasPreviousPage: hasPrev,
	}, nil
}

// ID converts the User's UUID to a GraphQL ID string.
// In the Go model, UserID is a uuid.UUID; in GraphQL, id is a String/ID.
func (r *userResolver) ID(ctx context.Context, obj *models.User) (string, error) {
	return obj.UserID.String(), nil
}

// CreatedAt converts the qmgo DefaultField timestamp to an ISO 8601 string.
// The DefaultField stores timestamps as time.Time, but GraphQL expects a string.
func (r *userResolver) CreatedAt(ctx context.Context, obj *models.User) (string, error) {
	return obj.CreateAt.Format(time.RFC3339), nil
}

// UpdatedAt converts the qmgo DefaultField timestamp to an ISO 8601 string.
func (r *userResolver) UpdatedAt(ctx context.Context, obj *models.User) (string, error) {
	return obj.UpdateAt.Format(time.RFC3339), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Operation returns generated.OperationResolver implementation.
func (r *Resolver) Operation() generated.OperationResolver { return &operationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type mutationResolver struct{ *Resolver }
type operationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
