package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/eventbus"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/graphql/generated"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/graphql/gqlctx"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/graphql/model"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/models"
)

// RevokeSession is the resolver for the revokeSession field.
func (r *mutationResolver) RevokeSession(ctx context.Context, id string) (bool, error) {
	return r.SessionResolver.RevokeSession(ctx, id)
}

// RevokeAllMySessions is the resolver for the revokeAllMySessions field.
func (r *mutationResolver) RevokeAllMySessions(ctx context.Context) (int, error) {
	return r.SessionResolver.RevokeAllMySessions(ctx)
}

// AdminRevokeSession is the resolver for the adminRevokeSession field.
func (r *mutationResolver) AdminRevokeSession(ctx context.Context, id string) (bool, error) {
	return r.SessionResolver.AdminRevokeSession(ctx, id)
}

// AdminRevokeAllUserSessions is the resolver for the adminRevokeAllUserSessions field.
func (r *mutationResolver) AdminRevokeAllUserSessions(ctx context.Context, userID string) (int, error) {
	return r.SessionResolver.AdminRevokeAllUserSessions(ctx, userID)
}

// MySessions is the resolver for the mySessions field.
func (r *queryResolver) MySessions(ctx context.Context, activeOnly *bool, first *int, after *string, last *int, before *string) (*model.SessionConnection, error) {
	return r.SessionResolver.MySessions(ctx, activeOnly, first, after, last, before)
}

// Sessions is the resolver for the sessions field.
func (r *queryResolver) Sessions(ctx context.Context, userID *string, search *string, activeOnly *bool, first *int, after *string, last *int, before *string) (*model.SessionConnection, error) {
	return r.SessionResolver.Sessions(ctx, userID, search, activeOnly, first, after, last, before)
}

// Session is the resolver for the session field.
func (r *queryResolver) Session(ctx context.Context, id string) (*models.Session, error) {
	return r.SessionResolver.Session(ctx, id)
}

// ID is the resolver for the id field.
func (r *sessionResolver) ID(ctx context.Context, obj *models.Session) (string, error) {
	return r.SessionResolver.ID(ctx, obj)
}

// UserID is the resolver for the userId field.
func (r *sessionResolver) UserID(ctx context.Context, obj *models.Session) (string, error) {
	return r.SessionResolver.UserID(ctx, obj)
}

// User is the resolver for the user field.
func (r *sessionResolver) User(ctx context.Context, obj *models.Session) (*models.User, error) {
	return r.SessionResolver.User(ctx, obj)
}

// Status is the resolver for the status field.
func (r *sessionResolver) Status(ctx context.Context, obj *models.Session) (models.SessionStatus, error) {
	return r.SessionResolver.Status(ctx, obj)
}

// LastActivityAt is the resolver for the lastActivityAt field.
func (r *sessionResolver) LastActivityAt(ctx context.Context, obj *models.Session) (*string, error) {
	return r.SessionResolver.LastActivityAt(ctx, obj)
}

// IsCurrent is the resolver for the isCurrent field.
func (r *sessionResolver) IsCurrent(ctx context.Context, obj *models.Session) (bool, error) {
	return r.SessionResolver.IsCurrent(ctx, obj)
}

// CreatedAt is the resolver for the createdAt field.
func (r *sessionResolver) CreatedAt(ctx context.Context, obj *models.Session) (string, error) {
	return r.SessionResolver.CreatedAt(ctx, obj)
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *sessionResolver) UpdatedAt(ctx context.Context, obj *models.Session) (string, error) {
	return r.SessionResolver.UpdatedAt(ctx, obj)
}

// MySessionChanged is the resolver for the mySessionChanged field.
// Streams session events for the caller's own sessions only.
func (r *subscriptionResolver) MySessionChanged(ctx context.Context) (<-chan *model.SessionEvent, error) {
	auth := gqlctx.AuthFromContext(ctx)
	if auth.UserID == "" {
		return nil, fmt.Errorf("unauthorized")
	}

	ch := make(chan *model.SessionEvent, 1)

	unsubscribe := r.EventBus.Subscribe(
		sessionTopics,
		func(_ context.Context, event eventbus.Event) {
			evt := toSessionEvent(event)
			// Only forward events for the caller's own sessions
			if evt.UserID != auth.UserID {
				return
			}

			// Fetch the full session from DB (use subscription ctx for cancellation)
			if evt.SessionID != "" {
				if sid, err := uuid.Parse(evt.SessionID); err == nil {
					if sess, err := r.SessionRepo.FindByID(ctx, sid); err == nil {
						// Status is bson:"-" so FindByID leaves it empty,
						// which the field resolver would turn into INACTIVE.
						// Derive it from the event topic instead.
						applySessionStatusFromTopic(&sess, event.Topic)
						evt.Session = &sess
					}
				}
			}

			select {
			case ch <- evt:
			case <-ctx.Done():
			}
		},
	)

	go func() {
		<-ctx.Done()
		unsubscribe()
		close(ch)
	}()

	return ch, nil
}

// SessionChanged is the resolver for the sessionChanged field.
// Streams session events for all users (admin only). Optionally filter by userId.
func (r *subscriptionResolver) SessionChanged(ctx context.Context, userID *string) (<-chan *model.SessionEvent, error) {
	auth := gqlctx.AuthFromContext(ctx)
	if auth.UserID == "" {
		return nil, fmt.Errorf("unauthorized")
	}

	ch := make(chan *model.SessionEvent, 1)

	unsubscribe := r.EventBus.Subscribe(
		sessionTopics,
		func(_ context.Context, event eventbus.Event) {
			evt := toSessionEvent(event)

			// If filtering by userId, skip events for other users
			if userID != nil && *userID != "" && evt.UserID != *userID {
				return
			}

			// Fetch the full session from DB (use subscription ctx for cancellation)
			if evt.SessionID != "" {
				if sid, err := uuid.Parse(evt.SessionID); err == nil {
					if sess, err := r.SessionRepo.FindByID(ctx, sid); err == nil {
						// Same rationale as MySessionChanged: FindByID leaves
						// the derived Status empty, so we set it from the topic.
						applySessionStatusFromTopic(&sess, event.Topic)
						evt.Session = &sess
					}
				}
			}

			select {
			case ch <- evt:
			case <-ctx.Done():
			}
		},
	)

	go func() {
		<-ctx.Done()
		unsubscribe()
		close(ch)
	}()

	return ch, nil
}

// Session returns generated.SessionResolver implementation.
func (r *Resolver) Session() generated.SessionResolver { return &sessionResolver{r} }

type sessionResolver struct{ *Resolver }
