package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"

	"github.com/vibe-c2/vibe-c2-core/core/pkg/graphql/model"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/mcp/skillchangelog"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/models"
)

// SnoozeSkillUpdate records that the caller dismissed the skill update prompt.
func (r *mutationResolver) SnoozeSkillUpdate(ctx context.Context, version int) (*models.User, error) {
	return r.UserResolver.SnoozeSkillUpdate(ctx, version)
}

// SkillChangelog is static for the life of the process: the history compiled
// into this binary. No entity resolver because there is nothing to authorize
// or look up.
func (r *queryResolver) SkillChangelog(ctx context.Context) (*model.SkillChangelog, error) {
	history := skillchangelog.Releases()
	releases := make([]*model.SkillRelease, 0, len(history))
	for _, rel := range history {
		releases = append(releases, &model.SkillRelease{
			Version: rel.Version,
			Date:    rel.Date,
			Notes:   rel.Notes,
		})
	}
	return &model.SkillChangelog{
		CurrentVersion: skillchangelog.Current(),
		Releases:       releases,
	}, nil
}
