package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"

	"github.com/vibe-c2/vibe-c2-core/core/pkg/graphql/model"
)

// SnoozeSkill is the resolver for the snoozeSkill field.
func (r *mutationResolver) SnoozeSkill(ctx context.Context, name string, version int) (*model.Skill, error) {
	return r.SkillResolver.Snooze(ctx, name, version)
}

// UnpublishSkill is the resolver for the unpublishSkill field.
func (r *mutationResolver) UnpublishSkill(ctx context.Context, name string) (*model.Skill, error) {
	return r.SkillResolver.SetUnpublished(ctx, name, true)
}

// RepublishSkill is the resolver for the republishSkill field.
func (r *mutationResolver) RepublishSkill(ctx context.Context, name string) (*model.Skill, error) {
	return r.SkillResolver.SetUnpublished(ctx, name, false)
}

// TransferSkill is the resolver for the transferSkill field.
func (r *mutationResolver) TransferSkill(ctx context.Context, name string, userID string) (*model.Skill, error) {
	return r.SkillResolver.Transfer(ctx, name, userID)
}

// SkillRegistry is the resolver for the skillRegistry field.
func (r *queryResolver) SkillRegistry(ctx context.Context) (*model.SkillRegistry, error) {
	return r.SkillResolver.Registry(ctx)
}

// SkillVersions is the resolver for the skillVersions field.
func (r *queryResolver) SkillVersions(ctx context.Context, name string) ([]*model.SkillVersion, error) {
	return r.SkillResolver.Versions(ctx, name)
}
