package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"

	"github.com/vibe-c2/vibe-c2-core/core/pkg/eventbus"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/graphql/gqlctx"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/graphql/model"
)

// SnoozeSkill is the resolver for the snoozeSkill field.
func (r *mutationResolver) SnoozeSkill(ctx context.Context, name string, version int) (*model.Skill, error) {
	return r.SkillResolver.Snooze(ctx, name, version)
}

// RemoveSkill is the resolver for the removeSkill field.
func (r *mutationResolver) RemoveSkill(ctx context.Context, name string) (*model.Skill, error) {
	return r.SkillResolver.Remove(ctx, name)
}

// TransferSkill is the resolver for the transferSkill field.
func (r *mutationResolver) TransferSkill(ctx context.Context, name string, userID string) (*model.Skill, error) {
	return r.SkillResolver.Transfer(ctx, name, userID)
}

// SkillRegistry is the resolver for the skillRegistry field.
func (r *queryResolver) SkillRegistry(ctx context.Context) (*model.SkillRegistry, error) {
	return r.SkillResolver.Registry(ctx)
}

// SkillVersions is the resolver for the skillVersions field.
func (r *queryResolver) SkillVersions(ctx context.Context, name string) ([]*model.SkillVersion, error) {
	return r.SkillResolver.Versions(ctx, name)
}

// SkillChanged is the resolver for the skillChanged field.
//
// Instance-wide, like the registry: a skill is a shared working method, not
// operation data, so there is no membership filter and authorization is the
// @hasPermission directive. Clients refetch the listing on every event
// because the interesting per-viewer part, whether they have the current
// version, is not in the payload.
func (r *subscriptionResolver) SkillChanged(ctx context.Context) (<-chan *model.SkillEvent, error) {
	auth := gqlctx.AuthFromContext(ctx)
	if auth.UserID == "" {
		return nil, fmt.Errorf("unauthorized")
	}

	ch := make(chan *model.SkillEvent, 1)

	unsubscribe := r.EventBus.Subscribe(
		skillTopics,
		func(_ context.Context, event eventbus.Event) {
			select {
			case ch <- toSkillEvent(event):
			case <-ctx.Done():
			}
		},
	)

	go func() {
		<-ctx.Done()
		unsubscribe()
		close(ch)
	}()

	return ch, nil
}
