package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/eventbus"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/graphql/generated"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/graphql/gqlctx"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/graphql/model"
)

// UserChanged is the resolver for the userChanged field.
//
// It subscribes to user create/update/delete events and streams them to the
// client as SSE frames. Each event includes the action, user ID, username,
// and (for non-DELETE) the full User object fetched from the database.
//
// Channel lifecycle:
//  1. We create a buffered channel and subscribe to the event bus
//  2. The event bus handler converts events and sends them on the channel
//  3. gqlgen reads from the channel and writes SSE frames to the HTTP response
//  4. When the client disconnects, gqlgen cancels ctx — our cleanup goroutine
//     unsubscribes from the event bus and closes the channel
func (r *subscriptionResolver) UserChanged(ctx context.Context) (<-chan *model.UserEvent, error) {
	auth := gqlctx.AuthFromContext(ctx)
	if auth.UserID == "" {
		return nil, fmt.Errorf("unauthorized")
	}

	ch := make(chan *model.UserEvent, 1)

	unsubscribe := r.EventBus.Subscribe(
		[]eventbus.Topic{
			eventbus.TopicUserCreated,
			eventbus.TopicUserUpdated,
			eventbus.TopicUserDeleted,
		},
		func(_ context.Context, event eventbus.Event) {
			evt := toUserEvent(event)

			// For non-DELETE events, fetch the full user from DB so the
			// frontend gets complete data without a follow-up query.
			if evt.Action != model.EventActionDeleted {
				if uid, err := uuid.Parse(evt.UserID); err == nil {
					if user, err := r.UserRepo.FindByID(context.Background(), uid); err == nil {
						evt.User = &user
					}
				}
			}

			select {
			case ch <- evt:
			case <-ctx.Done():
			}
		},
	)

	// Cleanup: when the client disconnects, unsubscribe and close the channel.
	go func() {
		<-ctx.Done()
		unsubscribe()
		close(ch)
	}()

	return ch, nil
}

// OperationChanged is the resolver for the operationChanged field.
//
// If operationID is provided, only events for that operation are delivered.
// Otherwise, events for all operations the caller is a member of are delivered.
// The membership set is captured at subscribe time — if the caller joins a new
// operation, they need to reconnect to receive events for it.
func (r *subscriptionResolver) OperationChanged(ctx context.Context, operationID *string) (<-chan *model.OperationEvent, error) {
	auth := gqlctx.AuthFromContext(ctx)
	if auth.UserID == "" {
		return nil, fmt.Errorf("unauthorized")
	}

	// Build the filter: either a single operation ID or the caller's full membership set.
	filter, err := r.buildOperationFilter(ctx, auth, operationID)
	if err != nil {
		return nil, err
	}

	ch := make(chan *model.OperationEvent, 1)

	unsubscribe := r.EventBus.Subscribe(
		[]eventbus.Topic{
			eventbus.TopicOperationCreated,
			eventbus.TopicOperationUpdated,
			eventbus.TopicOperationDeleted,
		},
		func(_ context.Context, event eventbus.Event) {
			evt := toOperationEvent(event)

			if evt.Action != model.EventActionDeleted {
				if opID, err := uuid.Parse(evt.OperationID); err == nil {
					if op, err := r.OperationRepo.FindByID(context.Background(), opID); err == nil {
						evt.Operation = &op
					}
				}
			}

			select {
			case ch <- evt:
			case <-ctx.Done():
			}
		},
		filter,
	)

	go func() {
		<-ctx.Done()
		unsubscribe()
		close(ch)
	}()

	return ch, nil
}

// OperationMemberChanged is the resolver for the operationMemberChanged field.
//
// Same scoping as OperationChanged — provide operationId to filter to one
// operation, or omit to receive events for all the caller's operations.
func (r *subscriptionResolver) OperationMemberChanged(ctx context.Context, operationID *string) (<-chan *model.OperationMemberEvent, error) {
	auth := gqlctx.AuthFromContext(ctx)
	if auth.UserID == "" {
		return nil, fmt.Errorf("unauthorized")
	}

	filter, err := r.buildOperationFilter(ctx, auth, operationID)
	if err != nil {
		return nil, err
	}

	ch := make(chan *model.OperationMemberEvent, 1)

	unsubscribe := r.EventBus.Subscribe(
		[]eventbus.Topic{
			eventbus.TopicOperationMemberAdded,
			eventbus.TopicOperationMemberRemoved,
			eventbus.TopicOperationMemberUpdated,
		},
		func(_ context.Context, event eventbus.Event) {
			evt := toOperationMemberEvent(event)

			select {
			case ch <- evt:
			case <-ctx.Done():
			}
		},
		filter,
	)

	go func() {
		<-ctx.Done()
		unsubscribe()
		close(ch)
	}()

	return ch, nil
}

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type subscriptionResolver struct{ *Resolver }
