package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"

	"github.com/vibe-c2/vibe-c2-core/core/pkg/graphql/generated"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/graphql/model"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/models"
)

// TaskBacklinks is the resolver for the taskBacklinks field on Credential.
// Cross-domain field: implemented in the task resolver (it owns the task
// repo and reverse-reference index); the credential resolver just delegates.
func (r *credentialResolver) TaskBacklinks(ctx context.Context, obj *models.Credential) ([]*models.Task, error) {
	return r.TaskResolver.TaskBacklinksForCredential(ctx, obj)
}

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, input model.CreateTaskInput) (*models.Task, error) {
	return r.TaskResolver.CreateTask(ctx, input)
}

// UpdateTask is the resolver for the updateTask field.
func (r *mutationResolver) UpdateTask(ctx context.Context, id string, input model.UpdateTaskInput) (*models.Task, error) {
	return r.TaskResolver.UpdateTask(ctx, id, input)
}

// ChangeTaskStage is the resolver for the changeTaskStage field.
func (r *mutationResolver) ChangeTaskStage(ctx context.Context, input model.ChangeTaskStageInput) (*models.Task, error) {
	return r.TaskResolver.ChangeTaskStage(ctx, input)
}

// SetTaskAssignees is the resolver for the setTaskAssignees field.
func (r *mutationResolver) SetTaskAssignees(ctx context.Context, taskID string, assigneeIds []string) (*models.Task, error) {
	return r.TaskResolver.SetTaskAssignees(ctx, taskID, assigneeIds)
}

// SetTaskWikiReferences is the resolver for the setTaskWikiReferences field.
func (r *mutationResolver) SetTaskWikiReferences(ctx context.Context, taskID string, wikiIds []string) (*models.Task, error) {
	return r.TaskResolver.SetTaskWikiReferences(ctx, taskID, wikiIds)
}

// SetTaskCredentialReferences is the resolver for the setTaskCredentialReferences field.
func (r *mutationResolver) SetTaskCredentialReferences(ctx context.Context, taskID string, credentialIds []string) (*models.Task, error) {
	return r.TaskResolver.SetTaskCredentialReferences(ctx, taskID, credentialIds)
}

// DeleteTask is the resolver for the deleteTask field.
func (r *mutationResolver) DeleteTask(ctx context.Context, id string) (bool, error) {
	return r.TaskResolver.DeleteTask(ctx, id)
}

// RestoreTask is the resolver for the restoreTask field.
func (r *mutationResolver) RestoreTask(ctx context.Context, id string) (*models.Task, error) {
	return r.TaskResolver.RestoreTask(ctx, id)
}

// PurgeTask is the resolver for the purgeTask field.
func (r *mutationResolver) PurgeTask(ctx context.Context, id string) (bool, error) {
	return r.TaskResolver.PurgeTask(ctx, id)
}

// Task is the resolver for the task field.
func (r *queryResolver) Task(ctx context.Context, id string) (*models.Task, error) {
	return r.TaskResolver.Task(ctx, id)
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context, operationID string, stage *models.TaskStage, search *string, first *int, after *string, last *int, before *string) (*model.TaskConnection, error) {
	return r.TaskResolver.Tasks(ctx, operationID, stage, search, first, after, last, before)
}

// TaskTrash is the resolver for the taskTrash field.
func (r *queryResolver) TaskTrash(ctx context.Context, operationID string, first *int, after *string, last *int, before *string) (*model.TaskConnection, error) {
	return r.TaskResolver.TaskTrash(ctx, operationID, first, after, last, before)
}

// TasksReferencingWikiDocument is the resolver for the tasksReferencingWikiDocument field.
func (r *queryResolver) TasksReferencingWikiDocument(ctx context.Context, documentID string) ([]*models.Task, error) {
	return r.TaskResolver.TasksReferencingWikiDocument(ctx, documentID)
}

// TasksReferencingCredential is the resolver for the tasksReferencingCredential field.
func (r *queryResolver) TasksReferencingCredential(ctx context.Context, credentialID string) ([]*models.Task, error) {
	return r.TaskResolver.TasksReferencingCredential(ctx, credentialID)
}

// TaskChanged is the resolver for the taskChanged field.
//
// Thin delegation — the actual implementation lives in subscription_helpers.go
// so gqlgen regen never has to round-trip it through this file.
func (r *subscriptionResolver) TaskChanged(ctx context.Context, operationID string) (<-chan *model.TaskEvent, error) {
	return r.taskChanged(ctx, operationID)
}

// ID is the resolver for the id field.
func (r *taskResolver) ID(ctx context.Context, obj *models.Task) (string, error) {
	return r.TaskResolver.ID(ctx, obj)
}

// OperationID is the resolver for the operationId field.
func (r *taskResolver) OperationID(ctx context.Context, obj *models.Task) (string, error) {
	return r.TaskResolver.OperationIDField(ctx, obj)
}

// Operation is the resolver for the operation field.
func (r *taskResolver) Operation(ctx context.Context, obj *models.Task) (*models.Operation, error) {
	return r.TaskResolver.Operation(ctx, obj)
}

// RiskScore is the resolver for the riskScore field.
func (r *taskResolver) RiskScore(ctx context.Context, obj *models.Task) (int, error) {
	return r.TaskResolver.RiskScore(ctx, obj)
}

// ProfitScore is the resolver for the profitScore field.
func (r *taskResolver) ProfitScore(ctx context.Context, obj *models.Task) (int, error) {
	return r.TaskResolver.ProfitScore(ctx, obj)
}

// Assignees is the resolver for the assignees field.
func (r *taskResolver) Assignees(ctx context.Context, obj *models.Task) ([]*models.User, error) {
	return r.TaskResolver.Assignees(ctx, obj)
}

// WikiReferences is the resolver for the wikiReferences field.
func (r *taskResolver) WikiReferences(ctx context.Context, obj *models.Task) ([]*models.WikiDocument, error) {
	return r.TaskResolver.WikiReferences(ctx, obj)
}

// CredentialReferences is the resolver for the credentialReferences field.
func (r *taskResolver) CredentialReferences(ctx context.Context, obj *models.Task) ([]*models.Credential, error) {
	return r.TaskResolver.CredentialReferences(ctx, obj)
}

// CreatedBy is the resolver for the createdBy field.
func (r *taskResolver) CreatedBy(ctx context.Context, obj *models.Task) (*models.User, error) {
	return r.TaskResolver.CreatedBy(ctx, obj)
}

// LastUpdatedBy is the resolver for the lastUpdatedBy field.
func (r *taskResolver) LastUpdatedBy(ctx context.Context, obj *models.Task) (*models.User, error) {
	return r.TaskResolver.LastUpdatedBy(ctx, obj)
}

// LastUpdatedAt is the resolver for the lastUpdatedAt field.
func (r *taskResolver) LastUpdatedAt(ctx context.Context, obj *models.Task) (*string, error) {
	return r.TaskResolver.LastUpdatedAt(ctx, obj)
}

// DeletedAt is the resolver for the deletedAt field.
func (r *taskResolver) DeletedAt(ctx context.Context, obj *models.Task) (*string, error) {
	return r.TaskResolver.DeletedAt(ctx, obj)
}

// CreatedAt is the resolver for the createdAt field.
func (r *taskResolver) CreatedAt(ctx context.Context, obj *models.Task) (string, error) {
	return r.TaskResolver.CreatedAt(ctx, obj)
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *taskResolver) UpdatedAt(ctx context.Context, obj *models.Task) (string, error) {
	return r.TaskResolver.UpdatedAt(ctx, obj)
}

// TaskBacklinks is the resolver for the taskBacklinks field on WikiDocument.
// Cross-domain field: implemented in the task resolver; the wiki document
// resolver just delegates.
func (r *wikiDocumentResolver) TaskBacklinks(ctx context.Context, obj *models.WikiDocument) ([]*models.Task, error) {
	return r.TaskResolver.TaskBacklinksForWikiDocument(ctx, obj)
}

// Task returns generated.TaskResolver implementation.
func (r *Resolver) Task() generated.TaskResolver { return &taskResolver{r} }

type taskResolver struct{ *Resolver }
