package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/eventbus"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/graphql/generated"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/graphql/gqlctx"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/graphql/model"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/models"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/repository"
)

// CreateCustomTimelineEvent is the resolver for the createCustomTimelineEvent field.
func (r *mutationResolver) CreateCustomTimelineEvent(ctx context.Context, operationID string, input model.CreateCustomTimelineEventInput) (*models.OperationEvent, error) {
	return r.TimelineResolver.CreateCustomTimelineEvent(ctx, operationID, input)
}

// UpdateCustomTimelineEvent is the resolver for the updateCustomTimelineEvent field.
func (r *mutationResolver) UpdateCustomTimelineEvent(ctx context.Context, id string, input model.UpdateCustomTimelineEventInput) (*models.OperationEvent, error) {
	return r.TimelineResolver.UpdateCustomTimelineEvent(ctx, id, input)
}

// DeleteCustomTimelineEvent is the resolver for the deleteCustomTimelineEvent field.
func (r *mutationResolver) DeleteCustomTimelineEvent(ctx context.Context, id string) (bool, error) {
	return r.TimelineResolver.DeleteCustomTimelineEvent(ctx, id)
}

// TimelineBuckets is the resolver for the timelineBuckets field.
func (r *queryResolver) TimelineBuckets(ctx context.Context, operationID string, granularity *repository.TimelineGranularity, timezone string, from *string, to *string, types []string, actorIds []string) ([]*model.TimelineBucket, error) {
	return r.TimelineResolver.TimelineBuckets(ctx, operationID, granularity, timezone, from, to, types, actorIds)
}

// TimelineEventsByDay is the resolver for the timelineEventsByDay field.
func (r *queryResolver) TimelineEventsByDay(ctx context.Context, operationID string, date string, timezone string, granularity *repository.TimelineGranularity, types []string, actorIds []string, first *int, after *string) (*model.TimelineEventConnection, error) {
	return r.TimelineResolver.TimelineEventsByDay(ctx, operationID, date, timezone, granularity, types, actorIds, first, after)
}

// TimelineEventAdded is the resolver for the timelineEventAdded field.
//
// Subscribes to TopicOperationEventLogged, refetches the persisted row by
// event id, and streams it to the client. The persistence subscriber
// publishes that topic only after the operation_events row has been
// committed, so this stream is always lossless with respect to what's in
// the database.
func (r *subscriptionResolver) TimelineEventAdded(ctx context.Context, operationID string) (<-chan *models.OperationEvent, error) {
	auth := gqlctx.AuthFromContext(ctx)
	if auth.UserID == "" {
		return nil, fmt.Errorf("unauthorized")
	}

	filter, err := r.buildOperationFilter(ctx, auth, &operationID)
	if err != nil {
		return nil, err
	}

	ch := make(chan *models.OperationEvent, 1)

	unsubscribe := r.EventBus.Subscribe(
		[]eventbus.Topic{eventbus.TopicOperationEventLogged},
		func(_ context.Context, event eventbus.Event) {
			p, ok := event.Payload.(eventbus.OperationEventLoggedPayload)
			if !ok {
				return
			}
			eventUID, err := uuid.Parse(p.EventID)
			if err != nil {
				return
			}
			row, err := r.TimelineResolver.FindByEventID(ctx, eventUID)
			if err != nil || row == nil {
				return
			}
			select {
			case ch <- row:
			case <-ctx.Done():
			}
		},
		filter,
	)

	go func() {
		<-ctx.Done()
		unsubscribe()
		close(ch)
	}()

	return ch, nil
}

// ID is the resolver for the id field.
func (r *timelineEventResolver) ID(ctx context.Context, obj *models.OperationEvent) (string, error) {
	return r.TimelineResolver.ID(ctx, obj)
}

// OperationID is the resolver for the operationId field.
func (r *timelineEventResolver) OperationID(ctx context.Context, obj *models.OperationEvent) (string, error) {
	return r.TimelineResolver.OperationIDField(ctx, obj)
}

// SubjectKind is the resolver for the subjectKind field.
func (r *timelineEventResolver) SubjectKind(ctx context.Context, obj *models.OperationEvent) (string, error) {
	return r.TimelineResolver.SubjectKind(ctx, obj)
}

// SubjectID is the resolver for the subjectId field.
func (r *timelineEventResolver) SubjectID(ctx context.Context, obj *models.OperationEvent) (string, error) {
	return r.TimelineResolver.SubjectID(ctx, obj)
}

// Actor is the resolver for the actor field.
func (r *timelineEventResolver) Actor(ctx context.Context, obj *models.OperationEvent) (*models.User, error) {
	return r.TimelineResolver.Actor(ctx, obj)
}

// OccurredAt is the resolver for the occurredAt field.
func (r *timelineEventResolver) OccurredAt(ctx context.Context, obj *models.OperationEvent) (string, error) {
	return r.TimelineResolver.OccurredAt(ctx, obj)
}

// Metadata is the resolver for the metadata field.
func (r *timelineEventResolver) Metadata(ctx context.Context, obj *models.OperationEvent) (string, error) {
	return r.TimelineResolver.Metadata(ctx, obj)
}

// TimelineEvent returns generated.TimelineEventResolver implementation.
func (r *Resolver) TimelineEvent() generated.TimelineEventResolver { return &timelineEventResolver{r} }

type timelineEventResolver struct{ *Resolver }
