package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"

	"github.com/vibe-c2/vibe-c2-core/core/pkg/graphql/generated"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/graphql/model"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/models"
)

// CreateWikiDocument is the resolver for the createWikiDocument field.
func (r *mutationResolver) CreateWikiDocument(ctx context.Context, operationID string, input model.CreateWikiDocumentInput) (*models.WikiDocument, error) {
	return r.WikiDocumentResolver.CreateWikiDocument(ctx, operationID, input)
}

// UpdateWikiDocument is the resolver for the updateWikiDocument field.
func (r *mutationResolver) UpdateWikiDocument(ctx context.Context, id string, input model.UpdateWikiDocumentInput) (*models.WikiDocument, error) {
	return r.WikiDocumentResolver.UpdateWikiDocument(ctx, id, input)
}

// ReorderWikiDocumentSiblings is the resolver for the reorderWikiDocumentSiblings field.
func (r *mutationResolver) ReorderWikiDocumentSiblings(ctx context.Context, input model.ReorderWikiDocumentSiblingsInput) ([]*models.WikiDocument, error) {
	return r.WikiDocumentResolver.ReorderWikiDocumentSiblings(ctx, input)
}

// DeleteWikiDocument is the resolver for the deleteWikiDocument field.
func (r *mutationResolver) DeleteWikiDocument(ctx context.Context, id string) (bool, error) {
	return r.WikiDocumentResolver.DeleteWikiDocument(ctx, id)
}

// RestoreWikiDocument is the resolver for the restoreWikiDocument field.
func (r *mutationResolver) RestoreWikiDocument(ctx context.Context, id string, cascade *bool) (*models.WikiDocument, error) {
	return r.WikiDocumentResolver.RestoreWikiDocument(ctx, id, cascade)
}

// PermanentlyDeleteWikiDocument is the resolver for the permanentlyDeleteWikiDocument field.
func (r *mutationResolver) PermanentlyDeleteWikiDocument(ctx context.Context, id string) (bool, error) {
	return r.WikiDocumentResolver.PermanentlyDeleteWikiDocument(ctx, id)
}

// EmptyWikiDocumentTrash is the resolver for the emptyWikiDocumentTrash field.
func (r *mutationResolver) EmptyWikiDocumentTrash(ctx context.Context, operationID string) (bool, error) {
	return r.WikiDocumentResolver.EmptyWikiDocumentTrash(ctx, operationID)
}

// CreateWikiDocumentBackup is the resolver for the createWikiDocumentBackup field.
func (r *mutationResolver) CreateWikiDocumentBackup(ctx context.Context, documentID string, description *string) (*models.WikiDocumentBackup, error) {
	return r.WikiDocumentResolver.CreateWikiDocumentBackup(ctx, documentID, description)
}

// RestoreWikiDocumentBackup is the resolver for the restoreWikiDocumentBackup field.
func (r *mutationResolver) RestoreWikiDocumentBackup(ctx context.Context, documentID string, backupID string) (*models.WikiDocument, error) {
	return r.WikiDocumentResolver.RestoreWikiDocumentBackup(ctx, documentID, backupID)
}

// DeleteWikiDocumentBackup is the resolver for the deleteWikiDocumentBackup field.
func (r *mutationResolver) DeleteWikiDocumentBackup(ctx context.Context, id string) (bool, error) {
	return r.WikiDocumentResolver.DeleteWikiDocumentBackup(ctx, id)
}

// TrackWikiDocumentVisit is the resolver for the trackWikiDocumentVisit field.
func (r *mutationResolver) TrackWikiDocumentVisit(ctx context.Context, documentID string) (*models.WikiDocumentVisit, error) {
	return r.WikiDocumentVisitResolver.TrackWikiDocumentVisit(ctx, documentID)
}

// WikiDocument is the resolver for the wikiDocument field.
func (r *queryResolver) WikiDocument(ctx context.Context, id string) (*models.WikiDocument, error) {
	return r.WikiDocumentResolver.WikiDocument(ctx, id)
}

// WikiDocuments is the resolver for the wikiDocuments field.
func (r *queryResolver) WikiDocuments(ctx context.Context, operationID string, parentDocumentID *string, search *string, first *int, after *string, last *int, before *string) (*model.WikiDocumentConnection, error) {
	return r.WikiDocumentResolver.WikiDocuments(ctx, operationID, parentDocumentID, search, first, after, last, before)
}

// WikiDocumentTree is the resolver for the wikiDocumentTree field.
func (r *queryResolver) WikiDocumentTree(ctx context.Context, operationID string) ([]*models.WikiDocument, error) {
	return r.WikiDocumentResolver.WikiDocumentTree(ctx, operationID)
}

// WikiDocumentChildren is the resolver for the wikiDocumentChildren field.
func (r *queryResolver) WikiDocumentChildren(ctx context.Context, operationID string, parentDocumentID *string) ([]*models.WikiDocument, error) {
	return r.WikiDocumentResolver.WikiDocumentChildren(ctx, operationID, parentDocumentID)
}

// WikiDocumentTreeRevealPath is the resolver for the wikiDocumentTreeRevealPath field.
func (r *queryResolver) WikiDocumentTreeRevealPath(ctx context.Context, documentID string) ([]*models.WikiDocument, error) {
	return r.WikiDocumentResolver.WikiDocumentTreeRevealPath(ctx, documentID)
}

// WikiDocumentTrashCount is the resolver for the wikiDocumentTrashCount field.
func (r *queryResolver) WikiDocumentTrashCount(ctx context.Context, operationID string) (int, error) {
	return r.WikiDocumentResolver.WikiDocumentTrashCount(ctx, operationID)
}

// WikiSearch is the resolver for the wikiSearch field.
func (r *queryResolver) WikiSearch(ctx context.Context, operationID string, scope *string, query string, offset *int, limit *int) (*model.WikiSearchConnection, error) {
	return r.WikiDocumentResolver.WikiSearch(ctx, operationID, scope, query, offset, limit)
}

// WikiDocumentTrash is the resolver for the wikiDocumentTrash field.
func (r *queryResolver) WikiDocumentTrash(ctx context.Context, operationID string, first *int, after *string, last *int, before *string) (*model.WikiDocumentConnection, error) {
	return r.WikiDocumentResolver.WikiDocumentTrash(ctx, operationID, first, after, last, before)
}

// WikiDocumentTrashedDescendants is the resolver for the wikiDocumentTrashedDescendants field.
func (r *queryResolver) WikiDocumentTrashedDescendants(ctx context.Context, documentID string) ([]*models.WikiDocument, error) {
	return r.WikiDocumentResolver.WikiDocumentTrashedDescendants(ctx, documentID)
}

// WikiDocumentBacklinks is the resolver for the wikiDocumentBacklinks field.
func (r *queryResolver) WikiDocumentBacklinks(ctx context.Context, documentID string) ([]*models.WikiDocument, error) {
	return r.WikiDocumentResolver.WikiDocumentBacklinks(ctx, documentID)
}

// WikiDocumentBackups is the resolver for the wikiDocumentBackups field.
func (r *queryResolver) WikiDocumentBackups(ctx context.Context, documentID string, trigger *models.WikiDocumentBackupTrigger, first *int, after *string, last *int, before *string) (*model.WikiDocumentBackupConnection, error) {
	return r.WikiDocumentResolver.WikiDocumentBackups(ctx, documentID, trigger, first, after, last, before)
}

// WikiDocumentBackup is the resolver for the wikiDocumentBackup field.
func (r *queryResolver) WikiDocumentBackup(ctx context.Context, id string) (*models.WikiDocumentBackup, error) {
	return r.WikiDocumentResolver.WikiDocumentBackup(ctx, id)
}

// WikiDocumentPresence is the resolver for the wikiDocumentPresence field.
func (r *queryResolver) WikiDocumentPresence(ctx context.Context, documentID string) (*model.WikiDocumentPresence, error) {
	return r.WikiDocumentResolver.WikiDocumentPresence(ctx, documentID)
}

// WikiOperationPresence is the resolver for the wikiOperationPresence field.
func (r *queryResolver) WikiOperationPresence(ctx context.Context, operationID string) ([]*model.WikiDocumentPresence, error) {
	return r.WikiDocumentResolver.WikiOperationPresence(ctx, operationID)
}

// WikiDocumentHistory is the resolver for the wikiDocumentHistory field.
func (r *queryResolver) WikiDocumentHistory(ctx context.Context, operationID string, offset *int, limit *int) (*model.WikiDocumentVisitConnection, error) {
	return r.WikiDocumentVisitResolver.WikiDocumentHistory(ctx, operationID, offset, limit)
}

// WikiDocumentChanged is the resolver for the wikiDocumentChanged field.
func (r *subscriptionResolver) WikiDocumentChanged(ctx context.Context, operationID string) (<-chan *model.WikiDocumentEvent, error) {
	return r.wikiDocumentChanged(ctx, operationID)
}

// WikiDocumentPresenceChanged is the resolver for the wikiDocumentPresenceChanged field.
func (r *subscriptionResolver) WikiDocumentPresenceChanged(ctx context.Context, operationID string) (<-chan *model.WikiDocumentPresenceEvent, error) {
	return r.wikiDocumentPresenceChanged(ctx, operationID)
}

// ID is the resolver for the id field.
func (r *wikiDocumentResolver) ID(ctx context.Context, obj *models.WikiDocument) (string, error) {
	return r.WikiDocumentResolver.WikiDocumentID(ctx, obj)
}

// OperationID is the resolver for the operationId field.
func (r *wikiDocumentResolver) OperationID(ctx context.Context, obj *models.WikiDocument) (string, error) {
	return r.WikiDocumentResolver.WikiDocumentOperationID(ctx, obj)
}

// ParentDocument is the resolver for the parentDocument field.
func (r *wikiDocumentResolver) ParentDocument(ctx context.Context, obj *models.WikiDocument) (*models.WikiDocument, error) {
	return r.WikiDocumentResolver.WikiDocumentParentDocument(ctx, obj)
}

// ParentDocumentID is the resolver for the parentDocumentId field.
func (r *wikiDocumentResolver) ParentDocumentID(ctx context.Context, obj *models.WikiDocument) (*string, error) {
	return r.WikiDocumentResolver.WikiDocumentParentDocumentID(ctx, obj)
}

// ChildDocuments is the resolver for the childDocuments field.
func (r *wikiDocumentResolver) ChildDocuments(ctx context.Context, obj *models.WikiDocument) ([]*models.WikiDocument, error) {
	return r.WikiDocumentResolver.WikiDocumentChildDocuments(ctx, obj)
}

// ChildCount is the resolver for the childCount field.
func (r *wikiDocumentResolver) ChildCount(ctx context.Context, obj *models.WikiDocument) (int, error) {
	return r.WikiDocumentResolver.WikiDocumentChildCount(ctx, obj)
}

// Backlinks is the resolver for the backlinks field.
func (r *wikiDocumentResolver) Backlinks(ctx context.Context, obj *models.WikiDocument) ([]*models.WikiDocument, error) {
	return r.WikiDocumentResolver.WikiDocumentBacklinksField(ctx, obj)
}

// Ancestors is the resolver for the ancestors field.
func (r *wikiDocumentResolver) Ancestors(ctx context.Context, obj *models.WikiDocument) ([]*model.WikiDocumentAncestor, error) {
	return r.WikiDocumentResolver.WikiDocumentAncestors(ctx, obj)
}

// CreatedBy is the resolver for the createdBy field.
func (r *wikiDocumentResolver) CreatedBy(ctx context.Context, obj *models.WikiDocument) (*models.User, error) {
	return r.WikiDocumentResolver.WikiDocumentCreatedBy(ctx, obj)
}

// LastUpdatedBy is the resolver for the lastUpdatedBy field.
func (r *wikiDocumentResolver) LastUpdatedBy(ctx context.Context, obj *models.WikiDocument) (*models.User, error) {
	return r.WikiDocumentResolver.WikiDocumentLastUpdatedBy(ctx, obj)
}

// LastUpdatedAt is the resolver for the lastUpdatedAt field.
func (r *wikiDocumentResolver) LastUpdatedAt(ctx context.Context, obj *models.WikiDocument) (*string, error) {
	return r.WikiDocumentResolver.WikiDocumentLastUpdatedAt(ctx, obj)
}

// LastBackupAt is the resolver for the lastBackupAt field.
func (r *wikiDocumentResolver) LastBackupAt(ctx context.Context, obj *models.WikiDocument) (*string, error) {
	return r.WikiDocumentResolver.WikiDocumentLastBackupAt(ctx, obj)
}

// DeletedAt is the resolver for the deletedAt field.
func (r *wikiDocumentResolver) DeletedAt(ctx context.Context, obj *models.WikiDocument) (*string, error) {
	return r.WikiDocumentResolver.WikiDocumentDeletedAt(ctx, obj)
}

// DeletedBy is the resolver for the deletedBy field.
func (r *wikiDocumentResolver) DeletedBy(ctx context.Context, obj *models.WikiDocument) (*models.User, error) {
	return r.WikiDocumentResolver.WikiDocumentDeletedBy(ctx, obj)
}

// CreatedAt is the resolver for the createdAt field.
func (r *wikiDocumentResolver) CreatedAt(ctx context.Context, obj *models.WikiDocument) (string, error) {
	return r.WikiDocumentResolver.WikiDocumentCreatedAt(ctx, obj)
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *wikiDocumentResolver) UpdatedAt(ctx context.Context, obj *models.WikiDocument) (string, error) {
	return r.WikiDocumentResolver.WikiDocumentUpdatedAt(ctx, obj)
}

// ID is the resolver for the id field.
func (r *wikiDocumentBackupResolver) ID(ctx context.Context, obj *models.WikiDocumentBackup) (string, error) {
	return r.WikiDocumentResolver.WikiDocumentBackupID(ctx, obj)
}

// DocumentID is the resolver for the documentId field.
func (r *wikiDocumentBackupResolver) DocumentID(ctx context.Context, obj *models.WikiDocumentBackup) (string, error) {
	return r.WikiDocumentResolver.WikiDocumentBackupDocumentID(ctx, obj)
}

// ContentLength is the resolver for the contentLength field.
func (r *wikiDocumentBackupResolver) ContentLength(ctx context.Context, obj *models.WikiDocumentBackup) (int, error) {
	return r.WikiDocumentResolver.WikiDocumentBackupContentLength(ctx, obj)
}

// CreatedBy is the resolver for the createdBy field.
func (r *wikiDocumentBackupResolver) CreatedBy(ctx context.Context, obj *models.WikiDocumentBackup) (*models.User, error) {
	return r.WikiDocumentResolver.WikiDocumentBackupCreatedBy(ctx, obj)
}

// CreatedAt is the resolver for the createdAt field.
func (r *wikiDocumentBackupResolver) CreatedAt(ctx context.Context, obj *models.WikiDocumentBackup) (string, error) {
	return r.WikiDocumentResolver.WikiDocumentBackupCreatedAt(ctx, obj)
}

// ID is the resolver for the id field.
func (r *wikiDocumentVisitResolver) ID(ctx context.Context, obj *models.WikiDocumentVisit) (string, error) {
	return r.WikiDocumentVisitResolver.WikiDocumentVisitID(ctx, obj)
}

// Document is the resolver for the document field.
func (r *wikiDocumentVisitResolver) Document(ctx context.Context, obj *models.WikiDocumentVisit) (*models.WikiDocument, error) {
	return r.WikiDocumentVisitResolver.WikiDocumentVisitDocument(ctx, obj)
}

// VisitedAt is the resolver for the visitedAt field.
func (r *wikiDocumentVisitResolver) VisitedAt(ctx context.Context, obj *models.WikiDocumentVisit) (string, error) {
	return r.WikiDocumentVisitResolver.WikiDocumentVisitVisitedAt(ctx, obj)
}

// WikiDocument returns generated.WikiDocumentResolver implementation.
func (r *Resolver) WikiDocument() generated.WikiDocumentResolver { return &wikiDocumentResolver{r} }

// WikiDocumentBackup returns generated.WikiDocumentBackupResolver implementation.
func (r *Resolver) WikiDocumentBackup() generated.WikiDocumentBackupResolver {
	return &wikiDocumentBackupResolver{r}
}

// WikiDocumentVisit returns generated.WikiDocumentVisitResolver implementation.
func (r *Resolver) WikiDocumentVisit() generated.WikiDocumentVisitResolver {
	return &wikiDocumentVisitResolver{r}
}

type wikiDocumentResolver struct{ *Resolver }
type wikiDocumentBackupResolver struct{ *Resolver }
type wikiDocumentVisitResolver struct{ *Resolver }
