// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"

	"github.com/vibe-c2/vibe-c2-core/core/pkg/models"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/pagination"
)

type APIKeyWithSecret struct {
	APIKey *models.APIKey `json:"apiKey"`
	Token  string         `json:"token"`
}

type CreateCredentialInput struct {
	Name     string                `json:"name"`
	Type     models.CredentialType `json:"type"`
	Username *string               `json:"username,omitempty"`
	Password *string               `json:"password,omitempty"`
	Keys     []*CredentialKeyInput `json:"keys,omitempty"`
	IsValid  *bool                 `json:"isValid,omitempty"`
	Tags     []string              `json:"tags,omitempty"`
}

type CreateCustomTimelineEventInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	OccurredAt  string  `json:"occurredAt"`
}

type CreateOperationInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type CreateSchemeNetworkPointInput struct {
	Names       []string `json:"names"`
	Description *string  `json:"description,omitempty"`
	Tags        []string `json:"tags,omitempty"`
}

type CreateSchemeNetworkPortInput struct {
	Number   int     `json:"number"`
	Protocol *string `json:"protocol,omitempty"`
	Service  *string `json:"service,omitempty"`
	Notes    *string `json:"notes,omitempty"`
}

type CreateUserInput struct {
	Username string   `json:"username"`
	Password string   `json:"password"`
	Roles    []string `json:"roles"`
	Active   *bool    `json:"active,omitempty"`
}

type CreateWikiDocumentInput struct {
	ParentDocumentID *string `json:"parentDocumentId,omitempty"`
	Title            string  `json:"title"`
	Content          *string `json:"content,omitempty"`
	Emoji            *string `json:"emoji,omitempty"`
	Color            *string `json:"color,omitempty"`
	Icon             *string `json:"icon,omitempty"`
	SortOrder        *string `json:"sortOrder,omitempty"`
}

type CredentialConnection struct {
	Edges      []*CredentialEdge    `json:"edges"`
	PageInfo   *pagination.PageInfo `json:"pageInfo"`
	TotalCount int                  `json:"totalCount"`
}

type CredentialEdge struct {
	Node   *models.Credential `json:"node"`
	Cursor string             `json:"cursor"`
}

type CredentialEvent struct {
	Action       EventAction        `json:"action"`
	CredentialID string             `json:"credentialId"`
	OperationID  string             `json:"operationId"`
	Credential   *models.Credential `json:"credential,omitempty"`
}

type CredentialKeyInput struct {
	Name    string `json:"name"`
	Content string `json:"content"`
}

type Mutation struct {
}

type OperationConnection struct {
	Edges      []*OperationEdge     `json:"edges"`
	PageInfo   *pagination.PageInfo `json:"pageInfo"`
	TotalCount int                  `json:"totalCount"`
}

type OperationEdge struct {
	Node   *models.Operation `json:"node"`
	Cursor string            `json:"cursor"`
}

type OperationEvent struct {
	Action      EventAction       `json:"action"`
	OperationID string            `json:"operationId"`
	Name        *string           `json:"name,omitempty"`
	Operation   *models.Operation `json:"operation,omitempty"`
}

type OperationMemberEvent struct {
	Action      EventAction `json:"action"`
	OperationID string      `json:"operationId"`
	UserID      string      `json:"userId"`
}

type Query struct {
}

type ReorderWikiDocumentSiblingsInput struct {
	OperationID      string   `json:"operationId"`
	ParentDocumentID *string  `json:"parentDocumentId,omitempty"`
	OrderedIds       []string `json:"orderedIds"`
}

type SchemeNetworkPointConnection struct {
	Edges      []*SchemeNetworkPointEdge `json:"edges"`
	PageInfo   *pagination.PageInfo      `json:"pageInfo"`
	TotalCount int                       `json:"totalCount"`
}

type SchemeNetworkPointEdge struct {
	Node   *models.SchemeNetworkPoint `json:"node"`
	Cursor string                     `json:"cursor"`
}

type SessionConnection struct {
	Edges      []*SessionEdge       `json:"edges"`
	PageInfo   *pagination.PageInfo `json:"pageInfo"`
	TotalCount int                  `json:"totalCount"`
}

type SessionEdge struct {
	Node   *models.Session `json:"node"`
	Cursor string          `json:"cursor"`
}

type SessionEvent struct {
	Action    EventAction     `json:"action"`
	SessionID string          `json:"sessionId"`
	UserID    string          `json:"userId"`
	Session   *models.Session `json:"session,omitempty"`
}

type Subscription struct {
}

type TimelineBucket struct {
	BucketStart string                `json:"bucketStart"`
	Count       int                   `json:"count"`
	TopicCounts []*TimelineTopicCount `json:"topicCounts"`
}

type TimelineEventConnection struct {
	Edges    []*TimelineEventEdge `json:"edges"`
	PageInfo *pagination.PageInfo `json:"pageInfo"`
}

type TimelineEventEdge struct {
	Node   *models.OperationEvent `json:"node"`
	Cursor string                 `json:"cursor"`
}

type TimelineTopicCount struct {
	Topic       string `json:"topic"`
	SubjectKind string `json:"subjectKind"`
	Count       int    `json:"count"`
}

type UpdateCredentialInput struct {
	Name     *string                `json:"name,omitempty"`
	Type     *models.CredentialType `json:"type,omitempty"`
	Username *string                `json:"username,omitempty"`
	Password *string                `json:"password,omitempty"`
	Keys     []*CredentialKeyInput  `json:"keys,omitempty"`
	IsValid  *bool                  `json:"isValid,omitempty"`
	Tags     []string               `json:"tags,omitempty"`
}

type UpdateCustomTimelineEventInput struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	OccurredAt  *string `json:"occurredAt,omitempty"`
}

type UpdateOperationInput struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
}

type UpdateSchemeNetworkPointInput struct {
	Names       []string `json:"names,omitempty"`
	Description *string  `json:"description,omitempty"`
	Tags        []string `json:"tags,omitempty"`
}

type UpdateSchemeNetworkPortInput struct {
	Number   *int    `json:"number,omitempty"`
	Protocol *string `json:"protocol,omitempty"`
	Service  *string `json:"service,omitempty"`
	Notes    *string `json:"notes,omitempty"`
}

type UpdateUserInput struct {
	Username *string   `json:"username,omitempty"`
	Password *string   `json:"password,omitempty"`
	Roles    []*string `json:"roles,omitempty"`
	Active   *bool     `json:"active,omitempty"`
}

type UpdateWikiDocumentInput struct {
	Title            *string `json:"title,omitempty"`
	Emoji            *string `json:"emoji,omitempty"`
	Color            *string `json:"color,omitempty"`
	Icon             *string `json:"icon,omitempty"`
	ParentDocumentID *string `json:"parentDocumentId,omitempty"`
	SortOrder        *string `json:"sortOrder,omitempty"`
}

type UserConnection struct {
	Edges      []*UserEdge          `json:"edges"`
	PageInfo   *pagination.PageInfo `json:"pageInfo"`
	TotalCount int                  `json:"totalCount"`
}

type UserEdge struct {
	Node   *models.User `json:"node"`
	Cursor string       `json:"cursor"`
}

type UserEvent struct {
	Action   EventAction  `json:"action"`
	UserID   string       `json:"userId"`
	Username *string      `json:"username,omitempty"`
	User     *models.User `json:"user,omitempty"`
}

type UserSuggestion struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}

type WikiDocumentAncestor struct {
	ID        string `json:"id"`
	Title     string `json:"title"`
	Emoji     string `json:"emoji"`
	Icon      string `json:"icon"`
	Color     string `json:"color"`
	IsDeleted bool   `json:"isDeleted"`
}

type WikiDocumentBackupConnection struct {
	Edges      []*WikiDocumentBackupEdge `json:"edges"`
	PageInfo   *pagination.PageInfo      `json:"pageInfo"`
	TotalCount int                       `json:"totalCount"`
}

type WikiDocumentBackupEdge struct {
	Node   *models.WikiDocumentBackup `json:"node"`
	Cursor string                     `json:"cursor"`
}

type WikiDocumentConnection struct {
	Edges      []*WikiDocumentEdge  `json:"edges"`
	PageInfo   *pagination.PageInfo `json:"pageInfo"`
	TotalCount int                  `json:"totalCount"`
}

type WikiDocumentEdge struct {
	Node   *models.WikiDocument `json:"node"`
	Cursor string               `json:"cursor"`
}

type WikiDocumentEditor struct {
	UserID      string `json:"userId"`
	Username    string `json:"username"`
	ConnectedAt string `json:"connectedAt"`
}

type WikiDocumentEvent struct {
	Action                   EventAction          `json:"action"`
	DocumentID               string               `json:"documentId"`
	OperationID              string               `json:"operationId"`
	ParentDocumentID         *string              `json:"parentDocumentId,omitempty"`
	PreviousParentDocumentID *string              `json:"previousParentDocumentId,omitempty"`
	Document                 *models.WikiDocument `json:"document,omitempty"`
}

type WikiDocumentPresence struct {
	DocumentID    string                `json:"documentId"`
	ActiveEditors []*WikiDocumentEditor `json:"activeEditors"`
}

type WikiDocumentPresenceEvent struct {
	DocumentID  string         `json:"documentId"`
	OperationID string         `json:"operationId"`
	UserID      string         `json:"userId"`
	Username    string         `json:"username"`
	Action      PresenceAction `json:"action"`
}

type WikiDocumentVisitConnection struct {
	Edges      []*WikiDocumentVisitEdge `json:"edges"`
	PageInfo   *pagination.PageInfo     `json:"pageInfo"`
	TotalCount int                      `json:"totalCount"`
}

type WikiDocumentVisitEdge struct {
	Node   *models.WikiDocumentVisit `json:"node"`
	Cursor string                    `json:"cursor"`
}

type WikiSearchConnection struct {
	Hits    []*WikiSearchHit `json:"hits"`
	Total   int              `json:"total"`
	HasMore bool             `json:"hasMore"`
}

type WikiSearchHit struct {
	Document    *models.WikiDocument    `json:"document"`
	Snippet     string                  `json:"snippet"`
	MatchRanges []*WikiSearchMatchRange `json:"matchRanges"`
	Score       *float64                `json:"score,omitempty"`
}

type WikiSearchMatchRange struct {
	Start int `json:"start"`
	End   int `json:"end"`
}

type EventAction string

const (
	EventActionCreated EventAction = "CREATED"
	EventActionUpdated EventAction = "UPDATED"
	EventActionDeleted EventAction = "DELETED"
)

var AllEventAction = []EventAction{
	EventActionCreated,
	EventActionUpdated,
	EventActionDeleted,
}

func (e EventAction) IsValid() bool {
	switch e {
	case EventActionCreated, EventActionUpdated, EventActionDeleted:
		return true
	}
	return false
}

func (e EventAction) String() string {
	return string(e)
}

func (e *EventAction) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EventAction(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EventAction", str)
	}
	return nil
}

func (e EventAction) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *EventAction) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e EventAction) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PresenceAction string

const (
	PresenceActionJoined PresenceAction = "JOINED"
	PresenceActionLeft   PresenceAction = "LEFT"
)

var AllPresenceAction = []PresenceAction{
	PresenceActionJoined,
	PresenceActionLeft,
}

func (e PresenceAction) IsValid() bool {
	switch e {
	case PresenceActionJoined, PresenceActionLeft:
		return true
	}
	return false
}

func (e PresenceAction) String() string {
	return string(e)
}

func (e *PresenceAction) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PresenceAction(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PresenceAction", str)
	}
	return nil
}

func (e PresenceAction) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PresenceAction) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PresenceAction) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type WikiDocumentSort string

const (
	WikiDocumentSortRecentlyCreated WikiDocumentSort = "RECENTLY_CREATED"
	WikiDocumentSortRecentlyUpdated WikiDocumentSort = "RECENTLY_UPDATED"
)

var AllWikiDocumentSort = []WikiDocumentSort{
	WikiDocumentSortRecentlyCreated,
	WikiDocumentSortRecentlyUpdated,
}

func (e WikiDocumentSort) IsValid() bool {
	switch e {
	case WikiDocumentSortRecentlyCreated, WikiDocumentSortRecentlyUpdated:
		return true
	}
	return false
}

func (e WikiDocumentSort) String() string {
	return string(e)
}

func (e *WikiDocumentSort) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WikiDocumentSort(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WikiDocumentSort", str)
	}
	return nil
}

func (e WikiDocumentSort) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *WikiDocumentSort) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e WikiDocumentSort) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
