// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"

	"github.com/vibe-c2/vibe-c2-core/core/pkg/models"
	"github.com/vibe-c2/vibe-c2-core/core/pkg/pagination"
)

type CreateOperationInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type CreateSchemeNetworkPointInput struct {
	Names       []string `json:"names"`
	Description *string  `json:"description,omitempty"`
	Tags        []string `json:"tags,omitempty"`
}

type CreateSchemeNetworkPortInput struct {
	Number   int     `json:"number"`
	Protocol *string `json:"protocol,omitempty"`
	Service  *string `json:"service,omitempty"`
	Notes    *string `json:"notes,omitempty"`
}

type CreateUserInput struct {
	Username string   `json:"username"`
	Password string   `json:"password"`
	Roles    []string `json:"roles"`
	Active   *bool    `json:"active,omitempty"`
}

type Mutation struct {
}

type OperationConnection struct {
	Edges      []*OperationEdge     `json:"edges"`
	PageInfo   *pagination.PageInfo `json:"pageInfo"`
	TotalCount int                  `json:"totalCount"`
}

type OperationEdge struct {
	Node   *models.Operation `json:"node"`
	Cursor string            `json:"cursor"`
}

type OperationEvent struct {
	Action      EventAction       `json:"action"`
	OperationID string            `json:"operationId"`
	Name        *string           `json:"name,omitempty"`
	Operation   *models.Operation `json:"operation,omitempty"`
}

type OperationMemberEvent struct {
	Action      EventAction `json:"action"`
	OperationID string      `json:"operationId"`
	UserID      string      `json:"userId"`
}

type Query struct {
}

type SchemeNetworkPointConnection struct {
	Edges      []*SchemeNetworkPointEdge `json:"edges"`
	PageInfo   *pagination.PageInfo      `json:"pageInfo"`
	TotalCount int                       `json:"totalCount"`
}

type SchemeNetworkPointEdge struct {
	Node   *models.SchemeNetworkPoint `json:"node"`
	Cursor string                     `json:"cursor"`
}

type Subscription struct {
}

type UpdateOperationInput struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
}

type UpdateSchemeNetworkPointInput struct {
	Names       []string `json:"names,omitempty"`
	Description *string  `json:"description,omitempty"`
	Tags        []string `json:"tags,omitempty"`
}

type UpdateSchemeNetworkPortInput struct {
	Number   *int    `json:"number,omitempty"`
	Protocol *string `json:"protocol,omitempty"`
	Service  *string `json:"service,omitempty"`
	Notes    *string `json:"notes,omitempty"`
}

type UpdateUserInput struct {
	Username *string   `json:"username,omitempty"`
	Password *string   `json:"password,omitempty"`
	Roles    []*string `json:"roles,omitempty"`
	Active   *bool     `json:"active,omitempty"`
}

type UserConnection struct {
	Edges      []*UserEdge          `json:"edges"`
	PageInfo   *pagination.PageInfo `json:"pageInfo"`
	TotalCount int                  `json:"totalCount"`
}

type UserEdge struct {
	Node   *models.User `json:"node"`
	Cursor string       `json:"cursor"`
}

type UserEvent struct {
	Action   EventAction  `json:"action"`
	UserID   string       `json:"userId"`
	Username *string      `json:"username,omitempty"`
	User     *models.User `json:"user,omitempty"`
}

type EventAction string

const (
	EventActionCreated EventAction = "CREATED"
	EventActionUpdated EventAction = "UPDATED"
	EventActionDeleted EventAction = "DELETED"
)

var AllEventAction = []EventAction{
	EventActionCreated,
	EventActionUpdated,
	EventActionDeleted,
}

func (e EventAction) IsValid() bool {
	switch e {
	case EventActionCreated, EventActionUpdated, EventActionDeleted:
		return true
	}
	return false
}

func (e EventAction) String() string {
	return string(e)
}

func (e *EventAction) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EventAction(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EventAction", str)
	}
	return nil
}

func (e EventAction) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *EventAction) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e EventAction) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
