// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/vibe-c2/vibe-c2-core/core/pkg/models"
)

type CreateOperationInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type CreateSchemeNetworkPointInput struct {
	Names       []string `json:"names"`
	Description *string  `json:"description,omitempty"`
	Tags        []string `json:"tags,omitempty"`
}

type CreateSchemeNetworkPortInput struct {
	Number   int     `json:"number"`
	Protocol *string `json:"protocol,omitempty"`
	Service  *string `json:"service,omitempty"`
	Notes    *string `json:"notes,omitempty"`
}

type CreateUserInput struct {
	Username string   `json:"username"`
	Password string   `json:"password"`
	Roles    []string `json:"roles"`
	Active   *bool    `json:"active,omitempty"`
}

type Mutation struct {
}

type OperationPagination struct {
	Operations      []*models.Operation `json:"operations"`
	TotalCount      int                 `json:"totalCount"`
	HasNextPage     bool                `json:"hasNextPage"`
	HasPreviousPage bool                `json:"hasPreviousPage"`
}

type Query struct {
}

type SchemeNetworkPointPagination struct {
	Points          []*models.SchemeNetworkPoint `json:"points"`
	TotalCount      int                          `json:"totalCount"`
	HasNextPage     bool                         `json:"hasNextPage"`
	HasPreviousPage bool                         `json:"hasPreviousPage"`
}

type UpdateOperationInput struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
}

type UpdateSchemeNetworkPointInput struct {
	Names       []string `json:"names,omitempty"`
	Description *string  `json:"description,omitempty"`
	Tags        []string `json:"tags,omitempty"`
}

type UpdateSchemeNetworkPortInput struct {
	Number   *int    `json:"number,omitempty"`
	Protocol *string `json:"protocol,omitempty"`
	Service  *string `json:"service,omitempty"`
	Notes    *string `json:"notes,omitempty"`
}

type UpdateUserInput struct {
	Username *string   `json:"username,omitempty"`
	Password *string   `json:"password,omitempty"`
	Roles    []*string `json:"roles,omitempty"`
	Active   *bool     `json:"active,omitempty"`
}

type UserPagination struct {
	Users           []*models.User `json:"users"`
	TotalCount      int            `json:"totalCount"`
	HasNextPage     bool           `json:"hasNextPage"`
	HasPreviousPage bool           `json:"hasPreviousPage"`
}
