// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/channel/sync": {
            "post": {
                "description": "Accepts an inbound.minion_message from a channel module and returns an outbound.minion_message. Payloads are opaque encrypted blobs; core currently returns a no-op outbound payload.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Channels"
                ],
                "summary": "Channel sync (data plane)",
                "parameters": [
                    {
                        "description": "Inbound minion message",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/protocol.InboundMinionMessage"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/protocol.OutboundMinionMessage"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/enroll": {
            "post": {
                "description": "Create the initial admin account. Only works when no users exist (cold startup).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Enrollment"
                ],
                "summary": "Enroll first admin",
                "parameters": [
                    {
                        "description": "Admin credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.EnrollRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.SessionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/graphql": {
            "get": {
                "description": "Serves the Altair GraphQL Client UI for interactive query testing. Development only.",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "GraphQL"
                ],
                "summary": "GraphQL Playground (Altair)",
                "responses": {}
            },
            "post": {
                "description": "Execute GraphQL queries and mutations. Authentication via httpOnly cookies; state-changing operations require an X-CSRF-Token header matching the csrf_token cookie.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GraphQL"
                ],
                "summary": "GraphQL endpoint",
                "responses": {}
            }
        },
        "/login": {
            "post": {
                "description": "Authenticate with username and password. Tokens are set as httpOnly cookies; CSRF token in a non-httpOnly cookie.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.SessionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/login/me": {
            "get": {
                "description": "Return the authenticated user's info.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Current user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.SessionResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/login/refresh": {
            "post": {
                "description": "Rotate the refresh token. Reads tokens from httpOnly cookies. Requires X-CSRF-Token header matching the csrf_token cookie.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Refresh tokens",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.SessionResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/logout": {
            "post": {
                "description": "Terminate the current session and clear auth cookies. Requires X-CSRF-Token header.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Logout",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.SuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/status": {
            "get": {
                "description": "Returns system state including whether initial enrollment has been completed.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Status"
                ],
                "summary": "System status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.StatusResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/wiki/collab-ticket": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Issue a short-lived JWT for Hocuspocus WebSocket authentication",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wiki"
                ],
                "summary": "Get collaboration ticket",
                "parameters": [
                    {
                        "description": "Document to collaborate on",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.collabTicketRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/wiki/export": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Streams a zip archive of markdown documents plus referenced attachments. The format matches the import flow so the result can be re-imported via POST /api/v1/wiki/import/outline. Pass ` + "`" + `rootId` + "`" + ` to limit the export to one document + descendants; omit it to export the whole operation's wiki.",
                "produces": [
                    "application/zip"
                ],
                "tags": [
                    "Wiki"
                ],
                "summary": "Export a wiki tree or subtree as an Outline-flavored markdown zip",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Target operation ID (UUID)",
                        "name": "operationId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Subtree root document ID (UUID). Omit for tree-wide export.",
                        "name": "rootId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/wiki/files": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Upload a non-image file to be attached to a wiki document. The original filename is preserved for downloads; bytes are stored as-is.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wiki"
                ],
                "summary": "Upload a wiki file attachment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Owning document ID (UUID)",
                        "name": "documentId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "File bytes (max 50MB by default)",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/controller.WikiFileUploadResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "413": {
                        "description": "Request Entity Too Large",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "415": {
                        "description": "Unsupported Media Type",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/wiki/files/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Streams the file bytes. Caller must be a member of the file's operation. Pass ?preview=1 for inline rendering of safe formats (PDF, text).",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "Wiki"
                ],
                "summary": "Fetch a wiki file attachment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "If true, serve inline for safe MIME types",
                        "name": "preview",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/wiki/images": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Upload an image to be embedded in a wiki document. Images are validated, sanitized (SVG) or re-encoded (raster, strips EXIF), and optionally downscaled.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wiki"
                ],
                "summary": "Upload a wiki image",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Owning document ID (UUID)",
                        "name": "documentId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Image bytes (png/jpeg/webp/gif/avif/svg, max 10MB)",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/controller.WikiImageUploadResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "413": {
                        "description": "Request Entity Too Large",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "415": {
                        "description": "Unsupported Media Type",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/wiki/images/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Streams the image bytes for an uploaded wiki image. Caller must be a member of the image's operation.",
                "produces": [
                    "image/*"
                ],
                "tags": [
                    "Wiki"
                ],
                "summary": "Fetch a wiki image",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Image ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/wiki/import/outline": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Imports an Outline (getoutline.com) markdown-format export zip into the target operation. All imported documents land under import/\u003cISO timestamp\u003e/\u003ccollection\u003e/. Requires operator+ role.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wiki"
                ],
                "summary": "Import an Outline workspace export",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Target operation ID (UUID)",
                        "name": "operationId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Outline markdown export zip",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/wikiimport.Report"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "413": {
                        "description": "Request Entity Too Large",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.WikiFileUploadResponse": {
            "type": "object",
            "properties": {
                "contentType": {
                    "type": "string"
                },
                "filename": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "controller.WikiImageUploadResponse": {
            "type": "object",
            "properties": {
                "height": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "width": {
                    "type": "integer"
                }
            }
        },
        "controller.collabTicketRequest": {
            "type": "object",
            "required": [
                "documentId"
            ],
            "properties": {
                "documentId": {
                    "type": "string"
                },
                "schemaVersion": {
                    "description": "SchemaVersion is the editor schema version compiled into the requesting\nclient. Absent (legacy/old clients that predate this field) decodes to 0.\nCompared against the document's ContentStateSchemaVersion to block clients\ntoo old to safely render — and thus edit — the stored content.",
                    "type": "integer"
                }
            }
        },
        "protocol.InboundMinionMessage": {
            "type": "object",
            "properties": {
                "encrypted_data": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "message_id": {
                    "type": "string"
                },
                "meta": {
                    "$ref": "#/definitions/protocol.MessageMeta"
                },
                "source": {
                    "$ref": "#/definitions/protocol.SourceInfo"
                },
                "timestamp": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "protocol.MessageMeta": {
            "type": "object",
            "additionalProperties": {}
        },
        "protocol.OutboundMinionMessage": {
            "type": "object",
            "properties": {
                "encrypted_data": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "message_id": {
                    "type": "string"
                },
                "meta": {
                    "$ref": "#/definitions/protocol.MessageMeta"
                },
                "timestamp": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "protocol.SourceInfo": {
            "type": "object",
            "properties": {
                "module": {
                    "type": "string"
                },
                "module_instance": {
                    "type": "string"
                },
                "tenant": {
                    "type": "string"
                },
                "transport": {
                    "type": "string"
                }
            }
        },
        "requests.EnrollRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "requests.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "responses.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "responses.SessionResponse": {
            "type": "object",
            "properties": {
                "permissions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "user_id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "responses.StatusResponse": {
            "type": "object",
            "properties": {
                "enrolled": {
                    "type": "boolean"
                }
            }
        },
        "responses.SuccessResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "wikiimport.Report": {
            "type": "object",
            "properties": {
                "createdDocs": {
                    "type": "integer"
                },
                "credentialsCreated": {
                    "type": "integer"
                },
                "credentialsReused": {
                    "type": "integer"
                },
                "credentialsSkipped": {
                    "type": "integer"
                },
                "credentialsTombstoned": {
                    "type": "integer"
                },
                "filesIngested": {
                    "type": "integer"
                },
                "imagesIngested": {
                    "type": "integer"
                },
                "importParentId": {
                    "type": "string"
                },
                "skipped": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/wikiimport.SkipRecord"
                    }
                },
                "skippedDocs": {
                    "type": "integer"
                },
                "timestampParentId": {
                    "type": "string"
                },
                "totalDocs": {
                    "type": "integer"
                },
                "warnings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/wikiimport.SkipRecord"
                    }
                }
            }
        },
        "wikiimport.SkipRecord": {
            "type": "object",
            "properties": {
                "path": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Bearer JWT token (e.g. \"Bearer eyJhb...\")",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "VibeC2 Core API",
	Description:      "Command-and-control core backend API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
