// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/channel/sync": {
            "post": {
                "description": "Accepts an inbound.minion_message from a channel module and returns an outbound.minion_message. Payloads are opaque encrypted blobs; core currently returns a no-op outbound payload.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Channels"
                ],
                "summary": "Channel sync (data plane)",
                "parameters": [
                    {
                        "description": "Inbound minion message",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/protocol.InboundMinionMessage"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/protocol.OutboundMinionMessage"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "instance is not a registered module",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "module registry unavailable",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/enroll": {
            "post": {
                "description": "Create the initial admin account. Only works when no users exist (cold startup).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Enrollment"
                ],
                "summary": "Enroll first admin",
                "parameters": [
                    {
                        "description": "Admin credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.EnrollRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.SessionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/graphql": {
            "get": {
                "description": "Serves the Altair GraphQL Client UI for interactive query testing. Development only.",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "GraphQL"
                ],
                "summary": "GraphQL Playground (Altair)",
                "responses": {}
            },
            "post": {
                "description": "Execute GraphQL queries and mutations. Authentication via httpOnly cookies; state-changing operations require an X-CSRF-Token header matching the csrf_token cookie.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GraphQL"
                ],
                "summary": "GraphQL endpoint",
                "responses": {}
            }
        },
        "/login": {
            "post": {
                "description": "Authenticate with username and password. Tokens are set as httpOnly cookies; CSRF token in a non-httpOnly cookie.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.SessionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/login/me": {
            "get": {
                "description": "Return the authenticated user's info.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Current user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.SessionResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/login/refresh": {
            "post": {
                "description": "Rotate the refresh token. Reads tokens from httpOnly cookies. Requires X-CSRF-Token header matching the csrf_token cookie.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Refresh tokens",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.SessionResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/logout": {
            "post": {
                "description": "Terminate the current session and clear auth cookies. Requires X-CSRF-Token header.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Logout",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.SuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/status": {
            "get": {
                "description": "Returns system state including whether initial enrollment has been completed.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Status"
                ],
                "summary": "System status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.StatusResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/wiki/collab-ticket": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Issue a short-lived JWT for Hocuspocus WebSocket authentication",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wiki"
                ],
                "summary": "Get collaboration ticket",
                "parameters": [
                    {
                        "description": "Document to collaborate on",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.collabTicketRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/wiki/files": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Upload a non-image file to be attached to a wiki document. The original filename is preserved for downloads; bytes are stored as-is.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wiki"
                ],
                "summary": "Upload a wiki file attachment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Owning document ID (UUID)",
                        "name": "documentId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "File bytes (max 50MB by default)",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/controller.WikiFileUploadResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "413": {
                        "description": "Request Entity Too Large",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "415": {
                        "description": "Unsupported Media Type",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/wiki/files/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Streams the file bytes. Caller must be a member of the file's operation. Pass ?preview=1 for inline rendering of safe formats (PDF, text, raster images).",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "Wiki"
                ],
                "summary": "Fetch a wiki file attachment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "If true, serve inline for safe MIME types",
                        "name": "preview",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/wiki/images": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Upload an image to be embedded in a wiki document. Images are validated, sanitized (SVG) or re-encoded (raster, strips EXIF), and optionally downscaled.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wiki"
                ],
                "summary": "Upload a wiki image",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Owning document ID (UUID)",
                        "name": "documentId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Image bytes (png/jpeg/webp/gif/avif/svg, max 10MB)",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/controller.WikiImageUploadResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "413": {
                        "description": "Request Entity Too Large",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "415": {
                        "description": "Unsupported Media Type",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/wiki/images/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Streams the image bytes for an uploaded wiki image. Caller must be a member of the image's operation.",
                "produces": [
                    "image/*"
                ],
                "tags": [
                    "Wiki"
                ],
                "summary": "Fetch a wiki image",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Image ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/wiki/transfer/exports": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Queues an export of the operation's wiki (or one subtree) as a native bundle or a markdown zip. Poll the returned job and download the archive when it is done. Viewer+ on the operation; credentials are embedded only when the caller is operator+.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wiki"
                ],
                "summary": "Start a wiki export job",
                "parameters": [
                    {
                        "description": "Export request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.ExportRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/controller.JobResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/wiki/transfer/imports": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Accepts a native bundle (.vibewiki.zip) or a markdown zip. The format is detected from the archive. Pages land under ` + "`" + `targetParentId` + "`" + `, at the root when it is absent, or in import/\u003ctimestamp\u003e/ when ` + "`" + `holdingPen=true` + "`" + `. Operator+ on the operation.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wiki"
                ],
                "summary": "Upload an archive and start a wiki import job",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Target operation ID (UUID)",
                        "name": "operationId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Page to import under (UUID). Omit for the root.",
                        "name": "targetParentId",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Land in import/\u003ctimestamp\u003e/ instead of targetParentId",
                        "name": "holdingPen",
                        "in": "query"
                    },
                    {
                        "type": "file",
                        "description": "Archive",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/controller.JobResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "413": {
                        "description": "Request Entity Too Large",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/wiki/transfer/jobs": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wiki"
                ],
                "summary": "List an operation's wiki transfer jobs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Operation ID (UUID)",
                        "name": "operationId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controller.JobResponse"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/wiki/transfer/jobs/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wiki"
                ],
                "summary": "Fetch one wiki transfer job",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.JobResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/wiki/transfer/jobs/{id}/download": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/zip"
                ],
                "tags": [
                    "Wiki"
                ],
                "summary": "Download a finished export",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.ExportRequest": {
            "type": "object",
            "required": [
                "operationId"
            ],
            "properties": {
                "format": {
                    "description": "Format is \"bundle\" (default) or \"markdown\".",
                    "type": "string"
                },
                "operationId": {
                    "type": "string"
                },
                "rootId": {
                    "description": "RootId scopes the export to one page and its descendants.",
                    "type": "string"
                }
            }
        },
        "controller.JobResponse": {
            "type": "object",
            "properties": {
                "artifactName": {
                    "description": "ArtifactName is the filename offered on download.",
                    "type": "string"
                },
                "artifactSize": {
                    "type": "integer"
                },
                "createAt": {
                    "type": "string"
                },
                "error": {
                    "description": "Error is the request-level failure message when Status is failed.",
                    "type": "string"
                },
                "expiresAt": {
                    "type": "string"
                },
                "finishedAt": {
                    "type": "string"
                },
                "format": {
                    "$ref": "#/definitions/models.WikiTransferFormat"
                },
                "id": {
                    "type": "string"
                },
                "jobId": {
                    "type": "string"
                },
                "kind": {
                    "$ref": "#/definitions/models.WikiTransferKind"
                },
                "operationId": {
                    "type": "string"
                },
                "progress": {
                    "$ref": "#/definitions/models.WikiTransferProgress"
                },
                "report": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "request": {
                    "$ref": "#/definitions/models.WikiTransferRequest"
                },
                "requestedById": {
                    "type": "string"
                },
                "startedAt": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/models.WikiTransferStatus"
                },
                "updateAt": {
                    "type": "string"
                }
            }
        },
        "controller.WikiFileUploadResponse": {
            "type": "object",
            "properties": {
                "contentType": {
                    "type": "string"
                },
                "filename": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "controller.WikiImageUploadResponse": {
            "type": "object",
            "properties": {
                "height": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "width": {
                    "type": "integer"
                }
            }
        },
        "controller.collabTicketRequest": {
            "type": "object",
            "required": [
                "documentId"
            ],
            "properties": {
                "documentId": {
                    "type": "string"
                },
                "schemaVersion": {
                    "description": "SchemaVersion is the editor schema version compiled into the requesting\nclient. Absent (legacy/old clients that predate this field) decodes to 0.\nCompared against the document's ContentStateSchemaVersion to block clients\ntoo old to safely render — and thus edit — the stored content.",
                    "type": "integer"
                }
            }
        },
        "models.WikiTransferFormat": {
            "type": "string",
            "enum": [
                "bundle",
                "markdown"
            ],
            "x-enum-varnames": [
                "WikiTransferBundle",
                "WikiTransferMarkdown"
            ]
        },
        "models.WikiTransferKind": {
            "type": "string",
            "enum": [
                "export",
                "import"
            ],
            "x-enum-varnames": [
                "WikiTransferExport",
                "WikiTransferImport"
            ]
        },
        "models.WikiTransferProgress": {
            "type": "object",
            "properties": {
                "done": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "models.WikiTransferRequest": {
            "type": "object",
            "properties": {
                "holdingPen": {
                    "description": "HoldingPen lands an import in import/\u003ctimestamp\u003e/ instead of\nTargetParentID.",
                    "type": "boolean"
                },
                "includeCredentials": {
                    "description": "IncludeCredentials embeds credential payloads in an export.",
                    "type": "boolean"
                },
                "rootDocumentId": {
                    "description": "RootDocumentID scopes an export to a subtree; nil exports the tree.",
                    "type": "string"
                },
                "targetParentId": {
                    "description": "TargetParentID places an import under a page; nil means the root.",
                    "type": "string"
                },
                "uploadFilename": {
                    "description": "UploadFilename is the name of the uploaded archive, for display.",
                    "type": "string"
                }
            }
        },
        "models.WikiTransferStatus": {
            "type": "string",
            "enum": [
                "queued",
                "running",
                "done",
                "failed"
            ],
            "x-enum-varnames": [
                "WikiTransferQueued",
                "WikiTransferRunning",
                "WikiTransferDone",
                "WikiTransferFailed"
            ]
        },
        "protocol.InboundMinionMessage": {
            "type": "object",
            "properties": {
                "encrypted_data": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "message_id": {
                    "type": "string"
                },
                "meta": {
                    "$ref": "#/definitions/protocol.MessageMeta"
                },
                "source": {
                    "$ref": "#/definitions/protocol.SourceInfo"
                },
                "timestamp": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "protocol.MessageMeta": {
            "type": "object",
            "additionalProperties": {}
        },
        "protocol.OutboundMinionMessage": {
            "type": "object",
            "properties": {
                "encrypted_data": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "message_id": {
                    "type": "string"
                },
                "meta": {
                    "$ref": "#/definitions/protocol.MessageMeta"
                },
                "timestamp": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "protocol.SourceInfo": {
            "type": "object",
            "properties": {
                "module": {
                    "type": "string"
                },
                "module_instance": {
                    "type": "string"
                },
                "tenant": {
                    "type": "string"
                },
                "transport": {
                    "type": "string"
                }
            }
        },
        "requests.EnrollRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "requests.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "responses.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "responses.SessionResponse": {
            "type": "object",
            "properties": {
                "permissions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "user_id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "responses.StatusResponse": {
            "type": "object",
            "properties": {
                "enrolled": {
                    "type": "boolean"
                }
            }
        },
        "responses.SuccessResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Bearer JWT token (e.g. \"Bearer eyJhb...\")",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "VibeC2 Core API",
	Description:      "Command-and-control core backend API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
