// Refcounted, deduplicated SSE subscription registry.
//
// Multiple React components subscribing to the same (document, variables)
// pair share a single underlying SSE connection. The stream is opened when
// the first listener attaches and torn down when the last one detaches.
// All data events fan out to every listener.
//
// Also owns:
//   - exponential backoff reconnect on transport errors
//   - immediate refresh-and-reconnect on 401
//   - gating on useConnectivityStore.waitUntilReachable() so reconnects
//     pause during a known outage (one shared health poll instead of N
//     parallel retries)
//   - document.visibilityState-based pause/resume so background tabs stop
//     holding connections
//
// The React-facing wrapper is use-subscription.ts.

import type { TypedDocumentNode } from "@graphql-typed-document-node/core"
import {
  graphqlSubscribe,
  SubscriptionHttpError,
} from "@/lib/graphql-subscribe"
import { tryRefresh } from "@/services/api-client"
import { useConnectivityStore } from "@/stores/connectivity"

const MIN_RETRY_DELAY_MS = 1_000
const MAX_RETRY_DELAY_MS = 30_000

type Listener<T> = (data: T) => void

interface SharedSubscription<T> {
  key: string
  document: TypedDocumentNode<T, unknown>
  variables: unknown
  listeners: Set<Listener<T>>
  controller: AbortController | null
  retryTimer: ReturnType<typeof setTimeout> | null
  retryDelay: number
  connecting: boolean
  disposed: boolean
}

// Stable per-document id for registry keys. Document objects are module-level
// constants generated by gql codegen, so WeakMap identity is reliable.
let nextDocId = 0
const docIdCache = new WeakMap<TypedDocumentNode<unknown, unknown>, number>()

function docId(doc: TypedDocumentNode<unknown, unknown>): number {
  let id = docIdCache.get(doc)
  if (id === undefined) {
    id = ++nextDocId
    docIdCache.set(doc, id)
  }
  return id
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const registry = new Map<string, SharedSubscription<any>>()

function keyFor(
  document: TypedDocumentNode<unknown, unknown>,
  variables: unknown,
): string {
  return `${docId(document)}:${JSON.stringify(variables ?? null)}`
}

/**
 * Subscribe to a GraphQL subscription. Returns an unsubscribe function.
 * Multiple callers with the same (document, variables) share one SSE stream.
 */
export function subscribe<TResult, TVariables>(
  document: TypedDocumentNode<TResult, TVariables>,
  variables: TVariables | undefined,
  listener: Listener<TResult>,
): () => void {
  const key = keyFor(
    document as TypedDocumentNode<unknown, unknown>,
    variables,
  )
  let sub = registry.get(key) as SharedSubscription<TResult> | undefined
  if (!sub) {
    sub = {
      key,
      document: document as TypedDocumentNode<TResult, unknown>,
      variables,
      listeners: new Set(),
      controller: null,
      retryTimer: null,
      retryDelay: MIN_RETRY_DELAY_MS,
      connecting: false,
      disposed: false,
    }
    registry.set(key, sub)
  }

  sub.listeners.add(listener)
  // First listener on a fresh entry — open the connection.
  if (sub.listeners.size === 1 && !sub.controller && !sub.retryTimer) {
    void connect(sub)
  }

  return () => {
    if (!sub) return
    sub.listeners.delete(listener)
    if (sub.listeners.size === 0) {
      teardown(sub)
    }
  }
}

function teardown<T>(sub: SharedSubscription<T>) {
  sub.disposed = true
  sub.controller?.abort()
  sub.controller = null
  if (sub.retryTimer) {
    clearTimeout(sub.retryTimer)
    sub.retryTimer = null
  }
  registry.delete(sub.key)
}

async function connect<T>(sub: SharedSubscription<T>) {
  if (sub.disposed || sub.connecting || sub.controller) return
  sub.connecting = true

  // Pause while tab is hidden — reopen via visibilitychange handler below.
  if (
    typeof document !== "undefined" &&
    document.visibilityState === "hidden"
  ) {
    sub.connecting = false
    return
  }

  // Wait until the backend is known reachable. This collapses N parallel
  // reconnect attempts into "all subs wait for the one health poll".
  await useConnectivityStore.getState().waitUntilReachable()
  if (sub.disposed) {
    sub.connecting = false
    return
  }

  const controller = graphqlSubscribe(sub.document, sub.variables, {
    onNext: (data) => {
      sub.retryDelay = MIN_RETRY_DELAY_MS
      // Copy the listeners to an array before iterating: a listener may
      // unsubscribe (mutating the Set) in response to the event.
      for (const listener of Array.from(sub.listeners)) {
        listener(data)
      }
    },
    onError: (err) => {
      sub.controller = null
      sub.connecting = false
      if (sub.disposed) return
      if (err instanceof SubscriptionHttpError && err.status === 401) {
        void refreshAndReconnect(sub)
        return
      }
      scheduleReconnect(sub)
    },
    onComplete: () => {
      sub.controller = null
      sub.connecting = false
      if (sub.disposed) return
      // Server ended the stream cleanly — just reconnect.
      scheduleReconnect(sub)
    },
  })

  if (sub.disposed) {
    controller.abort()
    sub.connecting = false
    return
  }
  sub.controller = controller
  sub.connecting = false
}

async function refreshAndReconnect<T>(sub: SharedSubscription<T>) {
  await tryRefresh()
  if (sub.disposed) return
  sub.retryDelay = MIN_RETRY_DELAY_MS
  void connect(sub)
}

function scheduleReconnect<T>(sub: SharedSubscription<T>) {
  if (sub.disposed || sub.retryTimer) return
  const jitter = Math.random() * 1_000
  const delay = sub.retryDelay + jitter
  sub.retryTimer = setTimeout(() => {
    sub.retryTimer = null
    if (sub.disposed) return
    void connect(sub)
  }, delay)
  sub.retryDelay = Math.min(sub.retryDelay * 2, MAX_RETRY_DELAY_MS)
}

// --- Tab visibility: pause SSE while hidden, resume when visible ---
// Background tabs holding open SSE connections waste server resources and
// are frequently throttled by the browser anyway.
if (typeof document !== "undefined") {
  document.addEventListener("visibilitychange", () => {
    if (document.visibilityState === "hidden") {
      for (const sub of registry.values()) {
        sub.controller?.abort()
        sub.controller = null
        if (sub.retryTimer) {
          clearTimeout(sub.retryTimer)
          sub.retryTimer = null
        }
      }
    } else {
      for (const sub of registry.values()) {
        if (
          !sub.disposed &&
          sub.listeners.size > 0 &&
          !sub.controller &&
          !sub.retryTimer
        ) {
          sub.retryDelay = MIN_RETRY_DELAY_MS
          void connect(sub)
        }
      }
    }
  })
}
