// Refcounted, deduplicated GraphQL subscription registry.
//
// Multiple React components subscribing to the same (document, variables)
// pair share a single underlying graphql-ws subscription. The subscription
// is opened on the singleton WebSocket client when the first listener
// attaches and disposed when the last one detaches. All data events fan
// out to every listener.
//
// The graphql-ws client (lib/graphql-ws-client.ts) owns transport-level
// concerns (connect, reconnect, exponential backoff, refresh-on-close,
// visibility-pause). This file only owns subscription-level concerns
// (dedup, fanout, refcount lifecycle).
//
// The React-facing wrapper is use-subscription.ts.

import type { TypedDocumentNode } from "@graphql-typed-document-node/core"
import { print } from "graphql"
import { getGraphQLWSClient } from "@/lib/graphql-ws-client"

type Listener<T> = (data: T) => void

interface SharedSubscription<T> {
  key: string
  query: string
  operationName: string | undefined
  variables: unknown
  listeners: Set<Listener<T>>
  dispose: (() => void) | null
}

// Stable per-document id for registry keys. Document objects are module-level
// constants generated by gql codegen, so WeakMap identity is reliable.
let nextDocId = 0
const docIdCache = new WeakMap<TypedDocumentNode<unknown, unknown>, number>()
// Cache the printed query string per document to avoid re-printing on every
// subscribe — print() walks the AST and is allocation-heavy.
const queryCache = new WeakMap<TypedDocumentNode<unknown, unknown>, string>()
const opNameCache = new WeakMap<TypedDocumentNode<unknown, unknown>, string | undefined>()

function docId(doc: TypedDocumentNode<unknown, unknown>): number {
  let id = docIdCache.get(doc)
  if (id === undefined) {
    id = ++nextDocId
    docIdCache.set(doc, id)
  }
  return id
}

function queryFor(doc: TypedDocumentNode<unknown, unknown>): string {
  let q = queryCache.get(doc)
  if (q === undefined) {
    q = print(doc)
    queryCache.set(doc, q)
  }
  return q
}

function opNameFor(
  doc: TypedDocumentNode<unknown, unknown>,
): string | undefined {
  if (opNameCache.has(doc)) return opNameCache.get(doc)
  const defs = (doc as unknown as { definitions: ReadonlyArray<{ kind: string; name?: { value?: string } }> }).definitions
  const opDef = defs.find((d) => d.kind === "OperationDefinition")
  const name = opDef?.name?.value
  opNameCache.set(doc, name)
  return name
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const registry = new Map<string, SharedSubscription<any>>()

function keyFor(
  document: TypedDocumentNode<unknown, unknown>,
  variables: unknown,
): string {
  return `${docId(document)}:${JSON.stringify(variables ?? null)}`
}

/**
 * Subscribe to a GraphQL subscription. Returns an unsubscribe function.
 * Multiple callers with the same (document, variables) share one underlying
 * graphql-ws subscription.
 */
export function subscribe<TResult, TVariables>(
  document: TypedDocumentNode<TResult, TVariables>,
  variables: TVariables | undefined,
  listener: Listener<TResult>,
): () => void {
  const doc = document as TypedDocumentNode<unknown, unknown>
  const key = keyFor(doc, variables)
  let sub = registry.get(key) as SharedSubscription<TResult> | undefined

  if (!sub) {
    sub = {
      key,
      query: queryFor(doc),
      operationName: opNameFor(doc),
      variables,
      listeners: new Set(),
      dispose: null,
    }
    registry.set(key, sub)
  }

  sub.listeners.add(listener)

  // First listener on a fresh entry — open the underlying graphql-ws sub.
  if (sub.listeners.size === 1 && !sub.dispose) {
    openSubscription(sub)
  }

  return () => {
    if (!sub) return
    sub.listeners.delete(listener)
    if (sub.listeners.size === 0) {
      teardown(sub)
    }
  }
}

function openSubscription<T>(sub: SharedSubscription<T>) {
  const client = getGraphQLWSClient()
  sub.dispose = client.subscribe<T>(
    {
      query: sub.query,
      variables: sub.variables as Record<string, unknown> | undefined,
      operationName: sub.operationName,
    },
    {
      next: (msg) => {
        if (!msg.data) return
        // Copy listeners to an array before iterating — a listener may
        // unsubscribe (mutating the Set) in response to the event.
        for (const listener of Array.from(sub.listeners)) {
          listener(msg.data as T)
        }
      },
      error: (err) => {
        // Transport-level retry is owned by the graphql-ws client. We don't
        // tear down on error — the client will reconnect and re-emit the
        // subscription (graphql-ws restarts active subscriptions on
        // reconnect automatically).
        //
        // Server-side GraphQL errors (e.g. `forbidden`) arrive here as an
        // array of objects with a `message` field. They do NOT trigger a
        // reconnect — the subscription simply stops delivering. Log them
        // so they don't fail silently: an auth misconfiguration on a
        // subscription used to be impossible to spot from the client.
        // Transport-level errors (CloseEvent / Error instances) are owned
        // by the graphql-ws client layer and intentionally not logged here.
        if (Array.isArray(err)) {
          const messages = err
            .map((e) => (e as { message?: string })?.message)
            .filter(Boolean)
            .join("; ")
          console.error(
            `[graphql-ws] subscription "${sub.operationName ?? "(anonymous)"}" rejected: ${messages}`,
          )
        }
      },
      complete: () => {
        // Server ended the stream cleanly. If listeners are still attached,
        // re-open. Otherwise let teardown happen on the natural detach.
        sub.dispose = null
        if (sub.listeners.size > 0) {
          openSubscription(sub)
        }
      },
    },
  )
}

function teardown<T>(sub: SharedSubscription<T>) {
  if (sub.dispose) {
    try {
      sub.dispose()
    } catch {
      // ignore — client may already be disposed
    }
    sub.dispose = null
  }
  registry.delete(sub.key)
}

// --- Tab visibility: pause subscriptions while hidden, resume on visible ---
// Background tabs holding open WebSockets waste server resources and are
// routinely throttled or killed by browsers anyway. Dispose every active
// subscription on hidden — graphql-ws closes the underlying socket once
// refcount reaches zero (lazy: true). On visible, re-open every subscription
// that still has listeners; getGraphQLWSClient() lazily rebuilds the socket
// on the first reopen.
if (typeof document !== "undefined") {
  document.addEventListener("visibilitychange", () => {
    if (document.visibilityState === "hidden") {
      for (const sub of registry.values()) {
        if (sub.dispose) {
          try {
            sub.dispose()
          } catch {
            // ignore — already disposed by client teardown
          }
          sub.dispose = null
        }
      }
    } else {
      for (const sub of registry.values()) {
        if (!sub.dispose && sub.listeners.size > 0) {
          openSubscription(sub)
        }
      }
    }
  })
}
